import type { SourceId, SourceMeta } from "./types";

/**
 * Catálogo das APIs públicas integradas — o agente auditor verifica cada uma contra
 * estes SLAs (frescor, disponibilidade, schema, faixa plausível).
 */
export const SOURCES: Record<SourceId, SourceMeta> = {
  ccee_pld: {
    id: "ccee_pld",
    name: "PLD horário",
    provider: "CCEE — Dados Abertos",
    region: "BR",
    category: "preço",
    endpoint: "https://dadosabertos.ccee.org.br/api/3/action/datastore_search",
    docs: "https://dadosabertos.ccee.org.br/dataset/pld_horario",
    license: "Dados abertos CCEE",
    cadence: "diária (D−1, ~tarde)",
    freshnessSlaHours: 48,
    support: "chamado na CCEE (atendimento@ccee.org.br · 0800 591 4185) com o código do erro e o IP da página de bloqueio",
    description: "Preço de Liquidação das Diferenças por submercado e hora — referência do mercado de curto prazo.",
  },
  ccee_pi: {
    id: "ccee_pi",
    name: "PLD horário oficial (Plataforma de Integração)",
    provider: "CCEE — Plataforma de Integração",
    region: "BR",
    category: "preço",
    endpoint: "https://servicos.ccee.org.br/ws/prec/PLDBSv1 (listarPLD)",
    docs: "https://github.com/devccee/postman-collections",
    license: "Serviço para agentes da CCEE (credencial + certificado digital)",
    cadence: "diária (D+1 publicado na véspera)",
    freshnessSlaHours: 30,
    requiresKey: "CCEE_PI_USERNAME",
    support: "atendimento da CCEE (0800 591 4185) — acesso à Plataforma de Integração e cadastro do certificado",
    description: "PLD oficial direto da CCEE por web service autenticado; quando configurado, substitui o PLD calculado pelo CMO.",
  },
  ons_cmo: {
    id: "ons_cmo",
    name: "CMO semi-horário (DESSEM)",
    provider: "ONS — Dados Abertos",
    region: "BR",
    category: "preço",
    endpoint: "https://dados.ons.org.br/dataset/cmo-semi-horario",
    docs: "https://dados.ons.org.br/dataset/cmo-semi-horario",
    license: "CC-BY (ONS)",
    cadence: "diária (programação D+1)",
    freshnessSlaHours: 48,
    description: "Custo Marginal de Operação por subsistema calculado pelo DESSEM — base de formação do PLD.",
  },
  ons_ear: {
    id: "ons_ear",
    name: "EAR diário por subsistema",
    provider: "ONS — Dados Abertos",
    region: "BR",
    category: "hidrologia",
    endpoint: "https://dados.ons.org.br/dataset/ear-diario-por-subsistema",
    docs: "https://dados.ons.org.br/dataset/ear-diario-por-subsistema",
    license: "CC-BY (ONS)",
    cadence: "diária",
    freshnessSlaHours: 72,
    description: "Energia armazenada nos reservatórios (% da capacidade) — principal driver estrutural do PLD.",
  },
  ons_ena: {
    id: "ons_ena",
    name: "ENA diária por subsistema",
    provider: "ONS — Dados Abertos",
    region: "BR",
    category: "hidrologia",
    endpoint: "https://dados.ons.org.br/dataset/ena-diario-por-subsistema",
    docs: "https://dados.ons.org.br/dataset/ena-diario-por-subsistema",
    license: "CC-BY (ONS)",
    cadence: "diária",
    freshnessSlaHours: 72,
    description: "Energia Natural Afluente bruta (% da MLT) — afluências que recompõem os reservatórios.",
  },
  ons_carga: {
    id: "ons_carga",
    name: "Curva de carga horária",
    provider: "ONS — Dados Abertos",
    region: "BR",
    category: "operação",
    endpoint: "https://dados.ons.org.br/dataset/curva-carga",
    docs: "https://dados.ons.org.br/dataset/curva-carga",
    license: "CC-BY (ONS)",
    cadence: "diária",
    freshnessSlaHours: 72,
    description: "Carga verificada por subsistema (MWmed) em base horária.",
  },
  energy_charts: {
    id: "energy_charts",
    name: "Preços day-ahead Europa",
    provider: "Fraunhofer ISE — Energy-Charts",
    region: "EU",
    category: "preço",
    endpoint: "https://api.energy-charts.info/price",
    docs: "https://api.energy-charts.info",
    license: "CC BY 4.0",
    cadence: "diária (leilão SDAC 12h CET) · 15 min",
    freshnessSlaHours: 30,
    description: "Preços do acoplamento de mercados europeu (SDAC) por zona de licitação.",
  },
  elexon_mid: {
    id: "elexon_mid",
    name: "Market Index Price (GB)",
    provider: "Elexon — BMRS Insights",
    region: "UK",
    category: "preço",
    endpoint: "https://data.elexon.co.uk/bmrs/api/v1/balancing/pricing/market-index",
    docs: "https://bmrs.elexon.co.uk/api-documentation",
    license: "Elexon BMRS Open Data",
    cadence: "30 min (quase tempo real)",
    freshnessSlaHours: 3,
    description: "Preço de referência de curto prazo do mercado britânico (APX).",
  },
  elexon_sysprice: {
    id: "elexon_sysprice",
    name: "System Buy/Sell Price (GB)",
    provider: "Elexon — BMRS Insights",
    region: "UK",
    category: "preço",
    endpoint: "https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/system-prices/{date}",
    docs: "https://bmrs.elexon.co.uk/api-documentation",
    license: "Elexon BMRS Open Data",
    cadence: "30 min (quase tempo real)",
    freshnessSlaHours: 3,
    description: "Preço de desequilíbrio (cash-out) — sinal de escassez em tempo real.",
  },
  uk_carbon: {
    id: "uk_carbon",
    name: "Intensidade de carbono (GB)",
    provider: "NESO — Carbon Intensity API",
    region: "UK",
    category: "carbono",
    endpoint: "https://api.carbonintensity.org.uk/intensity",
    docs: "https://carbon-intensity.github.io/api-definitions/",
    license: "CC BY 4.0",
    cadence: "30 min",
    freshnessSlaHours: 2,
    description: "gCO₂/kWh e mix de geração do sistema britânico.",
  },
  open_meteo: {
    id: "open_meteo",
    name: "Previsão meteorológica (hubs SIN)",
    provider: "Open-Meteo",
    region: "BR",
    category: "clima",
    endpoint: "https://api.open-meteo.com/v1/forecast",
    docs: "https://open-meteo.com/en/docs",
    license: "CC BY 4.0",
    cadence: "horária (ciclos NWP)",
    freshnessSlaHours: 6,
    description: "Temperatura (carga), vento a 100 m (eólica), irradiância (solar) e chuva (bacias).",
  },
  open_meteo_ens: {
    id: "open_meteo_ens",
    name: "Ensemble ECMWF — chuva nas bacias",
    provider: "Open-Meteo · ECMWF IFS 0.25°",
    region: "BR",
    category: "hidrologia",
    endpoint: "https://ensemble-api.open-meteo.com/v1/ensemble",
    docs: "https://open-meteo.com/en/docs/ensemble-api",
    license: "CC BY 4.0",
    cadence: "4×/dia",
    freshnessSlaHours: 12,
    description: "51 membros ECMWF: distribuição da chuva acumulada 15 dias nas principais bacias.",
  },
  bcb_fx: {
    id: "bcb_fx",
    name: "Câmbio USD/EUR/GBP",
    provider: "Banco Central do Brasil — SGS",
    region: "GLOBAL",
    category: "câmbio",
    endpoint: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.{codigo}/dados",
    docs: "https://dadosabertos.bcb.gov.br",
    license: "Dados abertos BCB",
    cadence: "diária (dias úteis)",
    freshnessSlaHours: 100,
    description: "Conversão de preços internacionais para R$/MWh.",
  },
  eia: {
    id: "eia",
    name: "Henry Hub & Brent",
    provider: "U.S. EIA — Open Data v2",
    region: "US",
    category: "combustíveis",
    endpoint: "https://api.eia.gov/v2",
    docs: "https://www.eia.gov/opendata/",
    license: "Domínio público (EUA)",
    cadence: "diária",
    freshnessSlaHours: 120,
    requiresKey: "EIA_API_KEY",
    description: "Gás natural e petróleo — custo marginal térmico (opcional, chave gratuita).",
  },
};

export const SOURCE_LIST = Object.values(SOURCES);
