S = r"""
wal.connect|Conectar carteira|Connect wallet|Conectar billetera|Connecter le portefeuille|Wallet verbinden|连接钱包|ウォレットを接続
wal.connectShort|Conectar|Connect|Conectar|Connecter|Verbinden|连接|接続
wal.wrongNet|rede errada|wrong network|red incorrecta|mauvais réseau|falsches Netzwerk|网络错误|ネットワークが違います
wal.signedOk|Acesso confirmado por assinatura|Access confirmed by signature|Acceso confirmado por firma|Accès confirmé par signature|Zugang per Signatur bestätigt|已通过签名确认访问|署名でアクセス確認済み
wal.signedNo|Acesso não confirmado|Access not confirmed|Acceso no confirmado|Accès non confirmé|Zugang nicht bestätigt|访问未确认|アクセス未確認
wal.switchTo|Trocar para {c}|Switch to {c}|Cambiar a {c}|Passer à {c}|Zu {c} wechseln|切换到 {c}|{c} に切り替え
wal.signing|Assine na carteira…|Sign in your wallet…|Firma en tu billetera…|Signez dans votre portefeuille…|In der Wallet signieren…|请在钱包中签名…|ウォレットで署名してください…
wal.confirmAccess|Confirmar acesso (assinatura)|Confirm access (signature)|Confirmar acceso (firma)|Confirmer l’accès (signature)|Zugang bestätigen (Signatur)|确认访问（签名）|アクセスを確認（署名）
wal.myPortfolio|Meu portfólio|My portfolio|Mi portafolio|Mon portefeuille|Mein Portfolio|我的投资组合|マイポートフォリオ
wal.transactions|Transações|Transactions|Transacciones|Transactions|Transaktionen|交易记录|取引履歴
wal.documents|Documentos|Documents|Documentos|Documents|Dokumente|文件|書類
wal.profile|Perfil|Profile|Perfil|Profil|Profil|个人资料|プロフィール
wal.logout|Sair|Sign out|Salir|Se déconnecter|Abmelden|退出|ログアウト
wal.via|Conectado via {w} · {c}|Connected via {w} · {c}|Conectado vía {w} · {c}|Connecté via {w} · {c}|Verbunden über {w} · {c}|已通过 {w} 连接 · {c}|{w} で接続中 · {c}
wal.copied|Copiado|Copied|Copiado|Copié|Kopiert|已复制|コピーしました
wal.copy|Copiar endereço|Copy address|Copiar dirección|Copier l’adresse|Adresse kopieren|复制地址|アドレスをコピー
wal.bscscan|Ver no BscScan|View on BscScan|Ver en BscScan|Voir sur BscScan|Auf BscScan ansehen|在 BscScan 查看|BscScan で表示
wal.siweIn|Entrar com assinatura (SIWE)|Sign in with signature (SIWE)|Entrar con firma (SIWE)|Se connecter par signature (SIWE)|Mit Signatur anmelden (SIWE)|签名登录 (SIWE)|署名でログイン (SIWE)
wal.session|Sessão autenticada por assinatura|Session authenticated by signature|Sesión autenticada por firma|Session authentifiée par signature|Sitzung per Signatur authentifiziert|会话已通过签名认证|署名で認証されたセッション
wal.sessionAria|sessão autenticada|authenticated session|sesión autenticada|session authentifiée|authentifizierte Sitzung|已认证会话|認証済みセッション
wal.disconnect|Desconectar|Disconnect|Desconectar|Déconnecter|Trennen|断开连接|切断
wal.cancelled|Conexão cancelada na carteira.|Connection cancelled in the wallet.|Conexión cancelada en la billetera.|Connexion annulée dans le portefeuille.|Verbindung in der Wallet abgebrochen.|已在钱包中取消连接。|ウォレットで接続がキャンセルされました。
wal.failed|Não foi possível conectar. Desbloqueie a carteira e tente de novo.|Could not connect. Unlock your wallet and try again.|No se pudo conectar. Desbloquea la billetera e inténtalo de nuevo.|Connexion impossible. Déverrouillez le portefeuille et réessayez.|Verbindung fehlgeschlagen. Wallet entsperren und erneut versuchen.|无法连接，请解锁钱包后重试。|接続できませんでした。ウォレットのロックを解除して再試行してください。
wal.recommended|recomendada|recommended|recomendada|recommandé|empfohlen|推荐|おすすめ
wal.opening|abrindo…|opening…|abriendo…|ouverture…|wird geöffnet…|正在打开…|起動中…
wal.none|Nenhuma carteira de extensão foi detectada neste navegador.|No browser-extension wallet was detected.|No se detectó ninguna billetera de extensión en este navegador.|Aucun portefeuille d’extension détecté dans ce navigateur.|Keine Browser-Wallet erkannt.|未在此浏览器中检测到扩展钱包。|このブラウザで拡張機能ウォレットが見つかりません。
wal.useBrowser|Usar a carteira do navegador|Use the browser wallet|Usar la billetera del navegador|Utiliser le portefeuille du navigateur|Browser-Wallet verwenden|使用浏览器钱包|ブラウザのウォレットを使う
wal.installOfficial|Instale uma carteira somente pelo site oficial:|Install a wallet only from its official website:|Instala una billetera solo desde el sitio oficial:|Installez un portefeuille uniquement depuis le site officiel :|Wallet nur von der offiziellen Website installieren:|请仅从官方网站安装钱包：|ウォレットは必ず公式サイトからインストールしてください：
wal.wcNote|Binance app, Trust Wallet e outras no celular, ou Ledger Live — via QR code|Binance app, Trust Wallet and other mobile wallets, or Ledger Live — via QR code|App de Binance, Trust Wallet y otras en el móvil, o Ledger Live — vía código QR|App Binance, Trust Wallet et autres sur mobile, ou Ledger Live — via QR code|Binance-App, Trust Wallet und andere mobile Wallets oder Ledger Live — per QR-Code|手机上的 Binance、Trust Wallet 等，或 Ledger Live——扫码连接|スマホの Binance アプリ・Trust Wallet など、または Ledger Live — QR コードで接続
wal.securityTitle|Segurança:|Security:|Seguridad:|Sécurité :|Sicherheit:|安全提示：|セキュリティ：
wal.securityText|a Aferi Capital nunca pede sua frase de recuperação (seed) nem chave privada. Para valores altos, use uma carteira de hardware (Ledger/Trezor) conectada à Rabby ou MetaMask. Confira sempre o endereço do contrato antes de assinar.|Aferi Capital will never ask for your recovery phrase (seed) or private key. For large amounts, use a hardware wallet (Ledger/Trezor) connected to Rabby or MetaMask. Always check the contract address before signing.|Aferi Capital nunca te pedirá tu frase de recuperación (seed) ni tu clave privada. Para montos altos, usa una billetera de hardware (Ledger/Trezor) conectada a Rabby o MetaMask. Verifica siempre la dirección del contrato antes de firmar.|Aferi Capital ne vous demandera jamais votre phrase de récupération (seed) ni votre clé privée. Pour des montants élevés, utilisez un portefeuille matériel (Ledger/Trezor) connecté à Rabby ou MetaMask. Vérifiez toujours l’adresse du contrat avant de signer.|Aferi Capital fragt niemals nach Ihrer Wiederherstellungsphrase (Seed) oder Ihrem privaten Schlüssel. Nutzen Sie für hohe Beträge eine Hardware-Wallet (Ledger/Trezor) mit Rabby oder MetaMask. Prüfen Sie vor dem Signieren stets die Vertragsadresse.|Aferi Capital 绝不会索要您的助记词或私钥。大额投资请使用连接 Rabby 或 MetaMask 的硬件钱包（Ledger/Trezor）。签名前请务必核对合约地址。|Aferi Capital がリカバリーフレーズ（シード）や秘密鍵を求めることは決してありません。高額の場合は Rabby または MetaMask に接続したハードウェアウォレット（Ledger/Trezor）をご利用ください。署名前に必ずコントラクトアドレスを確認してください。
wal.sigCancelled|Assinatura cancelada na carteira.|Signature cancelled in the wallet.|Firma cancelada en la billetera.|Signature annulée dans le portefeuille.|Signatur in der Wallet abgebrochen.|已在钱包中取消签名。|ウォレットで署名がキャンセルされました。
wal.sigFailed|Falha ao verificar a assinatura.|Could not verify the signature.|No se pudo verificar la firma.|Échec de la vérification de la signature.|Signatur konnte nicht geprüft werden.|签名验证失败。|署名を検証できませんでした。
wal.note.io_rabby|Simula cada transação antes de assinar e alerta contratos suspeitos. Funciona com Ledger/Trezor.|Simulates every transaction before signing and flags suspicious contracts. Works with Ledger/Trezor.|Simula cada transacción antes de firmar y alerta sobre contratos sospechosos. Funciona con Ledger/Trezor.|Simule chaque transaction avant signature et signale les contrats suspects. Compatible Ledger/Trezor.|Simuliert jede Transaktion vor dem Signieren und warnt vor verdächtigen Verträgen. Funktioniert mit Ledger/Trezor.|签名前模拟每笔交易并提示可疑合约，支持 Ledger/Trezor。|署名前に各取引をシミュレーションし、不審なコントラクトを警告。Ledger/Trezor に対応。
wal.note.io_metamask|Padrão do mercado; conecte uma Ledger/Trezor para a máxima segurança.|Industry standard; connect a Ledger/Trezor for maximum security.|Estándar del mercado; conecta una Ledger/Trezor para máxima seguridad.|Standard du marché ; connectez un Ledger/Trezor pour une sécurité maximale.|Marktstandard; für maximale Sicherheit Ledger/Trezor verbinden.|行业标准；连接 Ledger/Trezor 可获得最高安全性。|業界標準。Ledger/Trezor の接続で最高の安全性。
wal.note.com_binance_wallet|Carteira Web3 da Binance (autocustódia, MPC). Nativa da BNB Chain.|Binance’s Web3 wallet (self-custody, MPC). Native to BNB Chain.|Billetera Web3 de Binance (autocustodia, MPC). Nativa de BNB Chain.|Portefeuille Web3 de Binance (auto-conservation, MPC). Natif BNB Chain.|Web3-Wallet von Binance (Selbstverwahrung, MPC). Nativ für BNB Chain.|Binance 的 Web3 钱包（自托管，MPC），原生支持 BNB Chain。|Binance の Web3 ウォレット（セルフカストディ、MPC）。BNB Chain ネイティブ。
wal.note.com_trustwallet_app|Suporta BNB Chain nativamente.|Supports BNB Chain natively.|Soporta BNB Chain de forma nativa.|Prend en charge BNB Chain nativement.|Unterstützt BNB Chain nativ.|原生支持 BNB Chain。|BNB Chain をネイティブにサポート。
wal.note.com_okex_wallet|Suporta BNB Chain.|Supports BNB Chain.|Soporta BNB Chain.|Prend en charge BNB Chain.|Unterstützt BNB Chain.|支持 BNB Chain。|BNB Chain に対応。
wal.note.app_phantom|Focada em Solana; para a BNB Chain prefira Rabby, MetaMask ou Binance Wallet.|Solana-focused; for BNB Chain prefer Rabby, MetaMask or Binance Wallet.|Enfocada en Solana; para BNB Chain prefiere Rabby, MetaMask o Binance Wallet.|Axé sur Solana ; pour BNB Chain, préférez Rabby, MetaMask ou Binance Wallet.|Auf Solana fokussiert; für BNB Chain besser Rabby, MetaMask oder Binance Wallet.|专注 Solana；BNB Chain 建议使用 Rabby、MetaMask 或 Binance Wallet。|Solana 向け。BNB Chain には Rabby・MetaMask・Binance Wallet を推奨。
wal.siweStatement|Entrar na Aferi Capital. Esta assinatura não autoriza nenhuma transação nem movimenta fundos.|Sign in to Aferi Capital. This signature does not authorize any transaction or move any funds.|Entrar en Aferi Capital. Esta firma no autoriza ninguna transacción ni mueve fondos.|Connexion à Aferi Capital. Cette signature n’autorise aucune transaction et ne déplace aucun fonds.|Anmeldung bei Aferi Capital. Diese Signatur autorisiert keine Transaktion und bewegt keine Gelder.|登录 Aferi Capital。此签名不授权任何交易，也不会转移任何资金。|Aferi Capital にログイン。この署名は取引を承認せず、資金も移動しません。
"""
