S = r"""
como.meta|Como funciona|How it works|Cómo funciona|Comment ça marche|So funktioniert’s|运作方式|仕組み
como.metaDesc|Um processo simples, seguro e transparente para investir em usinas solares.|A simple, safe and transparent way to invest in solar plants.|Un proceso simple, seguro y transparente para invertir en plantas solares.|Un processus simple, sûr et transparent pour investir dans des centrales solaires.|Ein einfacher, sicherer und transparenter Weg, in Solarparks zu investieren.|简单、安全、透明地投资太阳能电站。|シンプル・安全・透明に太陽光発電所へ投資する方法。
como.h1|Como funciona|How it works|Cómo funciona|Comment ça marche|So funktioniert’s|运作方式|仕組み
como.sub|Quatro passos.|Four steps.|Cuatro pasos.|Quatre étapes.|Vier Schritte.|四个步骤。|4 つのステップ。
como.s1|Escolha uma usina|Choose a plant|Elige una planta|Choisissez une centrale|Park auswählen|选择电站|発電所を選ぶ
como.s1d|Compare rentabilidade, valor da cota e prazo.|Compare returns, share price and payback.|Compara rentabilidad, valor de la participación y plazo.|Comparez rendement, prix de la part et durée.|Rendite, Anteilspreis und Laufzeit vergleichen.|比较收益率、份额价格与期限。|利回り・1口価格・期間を比較。
como.s1c|Ver usinas|See plants|Ver plantas|Voir les centrales|Parks ansehen|查看电站|発電所を見る
como.s2|Simule|Simulate|Simula|Simulez|Berechnen|模拟|試算する
como.s2d|Veja quanto investe e quanto recebe por mês.|See how much you invest and receive each month.|Mira cuánto inviertes y cuánto recibes al mes.|Voyez combien vous investissez et recevez chaque mois.|Sehen Sie, wie viel Sie investieren und monatlich erhalten.|查看投资金额与每月收益。|投資額と毎月の受取額を確認。
como.s2c|Simular|Simulate|Simular|Simuler|Berechnen|模拟|試算
como.s3|Invista|Invest|Invierte|Investissez|Investieren|投资|投資する
como.s3d|Entre com sua carteira e confirme o aporte.|Sign in with your wallet and confirm the investment.|Entra con tu billetera y confirma el aporte.|Connectez votre portefeuille et confirmez l’apport.|Mit Wallet anmelden und Investition bestätigen.|使用钱包登录并确认投资。|ウォレットでログインし投資を確定。
como.s3c|Começar|Get started|Empezar|Commencer|Loslegen|开始|始める
como.s4|Receba todo mês|Get paid every month|Recibe cada mes|Recevez chaque mois|Jeden Monat Einnahmen|每月收益|毎月受け取る
como.s4d|Acompanhe tudo no seu portfólio.|Track everything in your portfolio.|Sigue todo en tu portafolio.|Suivez tout dans votre portefeuille.|Alles im Portfolio verfolgen.|在投资组合中跟踪一切。|ポートフォリオですべて確認。
como.s4c|Meu portfólio|My portfolio|Mi portafolio|Mon portefeuille|Mein Portfolio|我的投资组合|マイポートフォリオ
como.faq|Perguntas frequentes|Frequently asked questions|Preguntas frecuentes|Questions fréquentes|Häufige Fragen|常见问题|よくある質問
como.q1|O que eu compro ao investir?|What do I buy when I invest?|¿Qué compro al invertir?|Qu’est-ce que j’achète en investissant ?|Was kaufe ich, wenn ich investiere?|投资时我买的是什么？|投資で何を購入するのですか？
como.a1|Cotas digitais (tokens) de uma sociedade de propósito específico (SPE) dona da usina. A receita líquida da energia é distribuída em USDT na proporção das suas cotas.|Digital shares (tokens) of a special purpose vehicle (SPV) that owns the plant. Net energy revenue is distributed in USDT pro rata to your shares.|Participaciones digitales (tokens) de una sociedad de propósito específico (SPE) dueña de la planta. El ingreso neto de la energía se distribuye en USDT en proporción a tus participaciones.|Des parts numériques (jetons) d’une société de projet (SPV) propriétaire de la centrale. Le revenu net de l’énergie est distribué en USDT au prorata de vos parts.|Digitale Anteile (Token) an einer Projektgesellschaft (SPV), der der Park gehört. Der Nettoerlös wird anteilig in USDT ausgeschüttet.|拥有电站的特殊目的公司 (SPV) 的数字份额（代币）。电力净收入按您的份额比例以 USDT 分配。|発電所を保有する特別目的会社 (SPV) のデジタル持分（トークン）です。電力の純収益は持分に応じて USDT で分配されます。
como.q2|De onde vem o rendimento?|Where does the income come from?|¿De dónde viene el rendimiento?|D’où vient le revenu ?|Woher kommen die Erträge?|收益从何而来？|収益はどこから生まれますか？
como.a2|A usina gera créditos de energia que são cedidos a assinantes com desconto na conta de luz (geração compartilhada, Lei 14.300/2022). Descontados operação, seguro, impostos e taxa de administração, o restante vai para os cotistas.|The plant generates energy credits assigned to subscribers who get a discount on their power bill (shared generation, Brazil’s Law 14,300/2022). After operations, insurance, taxes and management fees, the rest goes to shareholders.|La planta genera créditos de energía que se ceden a suscriptores con descuento en la factura de luz (generación compartida, Ley 14.300/2022 de Brasil). Descontados operación, seguro, impuestos y comisión de administración, el resto va a los titulares.|La centrale produit des crédits d’énergie cédés à des abonnés qui bénéficient d’une réduction sur leur facture (production partagée, loi brésilienne 14.300/2022). Après exploitation, assurance, impôts et frais de gestion, le reste revient aux porteurs de parts.|Der Park erzeugt Energiegutschriften, die Abonnenten mit Rabatt auf die Stromrechnung erhalten (gemeinschaftliche Erzeugung, brasilianisches Gesetz 14.300/2022). Nach Betrieb, Versicherung, Steuern und Verwaltungsgebühr geht der Rest an die Anteilseigner.|电站产生的电力抵扣额度分配给订阅用户，用户享受电费折扣（共享发电，巴西第 14.300/2022 号法律）。扣除运营、保险、税费和管理费后，其余归份额持有人。|発電所が生む電力クレジットは、電気料金の割引を受ける契約者に割り当てられます（共有発電、ブラジル法 14.300/2022）。運営費・保険・税金・管理報酬を差し引いた残りが持分保有者に分配されます。
como.q3|Como a rentabilidade se compara à Selic?|How do returns compare with Brazil’s Selic rate?|¿Cómo se compara la rentabilidad con la Selic?|Comment le rendement se compare-t-il au taux Selic ?|Wie schneidet die Rendite im Vergleich zum Selic-Zins ab?|收益率与 Selic 利率相比如何？|利回りは Selic 金利と比べてどうですか？
como.a3|Cada usina mostra a rentabilidade estimada ao lado da Selic, do CDI, do Tesouro IPCA+ e da poupança, com o mesmo horizonte. O relatório em PDF traz essa comparação.|Each plant shows its estimated return next to Brazil’s Selic, CDI, inflation-linked Treasury (IPCA+) and savings rates over the same horizon. The PDF report includes this comparison.|Cada planta muestra la rentabilidad estimada junto a la Selic, el CDI, el Tesoro IPCA+ y el ahorro, con el mismo horizonte. El informe PDF incluye esa comparación.|Chaque centrale affiche son rendement estimé à côté du Selic, du CDI, du Trésor IPCA+ et de l’épargne brésiliens, sur le même horizon. Le rapport PDF inclut cette comparaison.|Jeder Park zeigt seine geschätzte Rendite neben Selic, CDI, inflationsgebundenen Staatsanleihen (IPCA+) und Sparbuch über denselben Zeitraum. Der PDF-Bericht enthält den Vergleich.|每座电站都会在相同期限内将预计收益率与巴西 Selic、CDI、通胀挂钩国债 (IPCA+) 及储蓄利率并列展示，PDF 报告中也包含此对比。|各発電所は、同じ期間でブラジルの Selic・CDI・インフレ連動国債 (IPCA+)・普通預金と並べて推定利回りを表示します。PDF レポートにもこの比較があります。
como.q4|E se a oferta não atingir a meta?|What if the offer misses its target?|¿Y si la oferta no alcanza la meta?|Et si l’offre n’atteint pas son objectif ?|Und wenn das Angebot sein Ziel verfehlt?|如果认购未达目标怎么办？|募集が目標に届かなかったら？
como.a4|O contrato devolve integralmente o valor de todos os investidores. Também é possível desistir até 5 dias após cada aporte.|The contract refunds every investor in full. You can also withdraw up to 5 days after each investment.|El contrato devuelve íntegramente el valor a todos los inversores. También es posible desistir hasta 5 días después de cada aporte.|Le contrat rembourse intégralement tous les investisseurs. Vous pouvez aussi vous rétracter jusqu’à 5 jours après chaque apport.|Der Vertrag erstattet allen Anlegern den vollen Betrag. Zudem ist ein Widerruf bis 5 Tage nach jeder Einzahlung möglich.|合约会向所有投资者全额退款。每笔投资后 5 天内也可撤回。|コントラクトが全投資家に全額返金します。各投資から 5 日以内の撤回も可能です。
como.q5|Preciso de carteira cripto?|Do I need a crypto wallet?|¿Necesito una billetera cripto?|Ai-je besoin d’un portefeuille crypto ?|Brauche ich eine Krypto-Wallet?|需要加密钱包吗？|暗号資産ウォレットは必要ですか？
como.a5|Sim. O login e os aportes usam uma carteira da BNB Chain (Binance Wallet, MetaMask, Rabby ou Trust). Nunca pedimos sua frase de recuperação.|Yes. Sign-in and investments use a BNB Chain wallet (Binance Wallet, MetaMask, Rabby or Trust). We never ask for your recovery phrase.|Sí. El inicio de sesión y los aportes usan una billetera de BNB Chain (Binance Wallet, MetaMask, Rabby o Trust). Nunca pedimos tu frase de recuperación.|Oui. La connexion et les apports utilisent un portefeuille BNB Chain (Binance Wallet, MetaMask, Rabby ou Trust). Nous ne demandons jamais votre phrase de récupération.|Ja. Anmeldung und Einzahlungen erfolgen mit einer BNB-Chain-Wallet (Binance Wallet, MetaMask, Rabby oder Trust). Wir fragen nie nach Ihrer Wiederherstellungsphrase.|需要。登录和投资均使用 BNB Chain 钱包（Binance Wallet、MetaMask、Rabby 或 Trust）。我们绝不索要您的助记词。|はい。ログインと投資には BNB Chain のウォレット（Binance Wallet、MetaMask、Rabby、Trust）を使います。リカバリーフレーズを求めることはありません。
como.more|Detalhes de contratos e proteções em|Contract details and protections in|Detalles de contratos y protecciones en|Détails des contrats et protections dans|Vertragsdetails und Schutzmechanismen unter|合约详情与保障措施见|契約と保護の詳細は
como.moreLink|Segurança|Security|Seguridad|Sécurité|Sicherheit|安全|セキュリティ
about.meta|Sobre nós|About us|Sobre nosotros|À propos|Über uns|关于我们|会社概要
about.metaDesc|A Aferi Capital conecta pessoas a projetos reais de geração de energia limpa.|Aferi Capital connects people to real clean-energy generation projects.|Aferi Capital conecta a las personas con proyectos reales de generación de energía limpia.|Aferi Capital relie les particuliers à de vrais projets de production d’énergie propre.|Aferi Capital verbindet Menschen mit echten Projekten für saubere Energie.|Aferi Capital 将人们与真实的清洁能源发电项目连接起来。|Aferi Capital は人々と実際のクリーンエネルギー発電プロジェクトをつなぎます。
about.h1|Sobre a Aferi Capital|About Aferi Capital|Sobre Aferi Capital|À propos d’Aferi Capital|Über Aferi Capital|关于 Aferi Capital|Aferi Capital について
about.tag|Energia solar que gera valor.|Solar energy that creates value.|Energía solar que genera valor.|L’énergie solaire qui crée de la valeur.|Solarenergie, die Wert schafft.|创造价值的太阳能。|価値を生む太陽光エネルギー。
about.p1|A Aferi Capital é uma plataforma de investimentos em usinas solares, conectando pessoas a projetos reais de geração de energia limpa e renovável.|Aferi Capital is an investment platform for solar plants, connecting people to real clean and renewable energy projects.|Aferi Capital es una plataforma de inversión en plantas solares que conecta a las personas con proyectos reales de energía limpia y renovable.|Aferi Capital est une plateforme d’investissement dans des centrales solaires, qui relie les particuliers à de vrais projets d’énergie propre et renouvelable.|Aferi Capital ist eine Investmentplattform für Solarparks und verbindet Menschen mit echten Projekten für saubere, erneuerbare Energie.|Aferi Capital 是太阳能电站投资平台，连接人们与真实的清洁可再生能源项目。|Aferi Capital は太陽光発電所への投資プラットフォームで、人々と実際のクリーンな再生可能エネルギー事業をつなぎます。
about.p2|Nosso propósito é tornar o investimento em energia solar mais acessível, transparente e seguro, com uma equipe especializada em todo o processo: da análise técnica da usina ao acompanhamento das distribuições.|Our purpose is to make solar investing more accessible, transparent and safe, with a specialist team across the whole process: from technical due diligence to distribution tracking.|Nuestro propósito es hacer la inversión en energía solar más accesible, transparente y segura, con un equipo especializado en todo el proceso: del análisis técnico de la planta al seguimiento de las distribuciones.|Notre mission : rendre l’investissement solaire plus accessible, transparent et sûr, avec une équipe spécialisée sur tout le parcours, de l’analyse technique au suivi des distributions.|Unser Ziel ist es, Solarinvestments zugänglicher, transparenter und sicherer zu machen – mit einem Fachteam für den gesamten Prozess, von der technischen Prüfung bis zur Ausschüttung.|我们的使命是让太阳能投资更普惠、透明、安全，专业团队覆盖全流程：从电站技术分析到收益分配跟踪。|私たちの目的は、太陽光投資をより身近で透明かつ安全にすることです。発電所の技術分析から分配のフォローまで、専門チームが全工程を担います。
about.p3|Cada número da plataforma vem de um modelo aberto, alimentado por dados públicos de satélite (NASA POWER, PVGIS), do Banco Central e do IBGE — e cada relatório pode ser verificado por qualquer pessoa.|Every number on the platform comes from an open model fed by public satellite data (NASA POWER, PVGIS), Brazil’s Central Bank and IBGE — and anyone can verify every report.|Cada número de la plataforma proviene de un modelo abierto, alimentado por datos públicos de satélite (NASA POWER, PVGIS), del Banco Central de Brasil y del IBGE, y cualquiera puede verificar cada informe.|Chaque chiffre de la plateforme provient d’un modèle ouvert alimenté par des données publiques satellitaires (NASA POWER, PVGIS), de la Banque centrale du Brésil et de l’IBGE — et chacun peut vérifier chaque rapport.|Jede Zahl stammt aus einem offenen Modell mit öffentlichen Satellitendaten (NASA POWER, PVGIS), Daten der brasilianischen Zentralbank und des IBGE – und jeder kann jeden Bericht prüfen.|平台上的每个数字都来自开放模型，使用公开卫星数据（NASA POWER、PVGIS）、巴西央行和 IBGE 数据，任何人都可以验证每份报告。|プラットフォームの数値はすべて、公開衛星データ（NASA POWER、PVGIS）、ブラジル中央銀行、IBGE のデータを用いたオープンなモデルによるもので、誰でも各レポートを検証できます。
about.boxTitle|Ativos reais de energia solar, analisados com dados abertos e acompanhados de perto.|Real solar assets, analyzed with open data and closely monitored.|Activos reales de energía solar, analizados con datos abiertos y seguidos de cerca.|Des actifs solaires réels, analysés avec des données ouvertes et suivis de près.|Echte Solaranlagen, mit offenen Daten analysiert und eng begleitet.|真实的太阳能资产，基于公开数据分析并密切跟踪。|実在の太陽光資産を、オープンデータで分析し、きめ細かく管理。
about.boxText|Cada usina publicada passa por levantamento técnico, econômico e regulatório antes de chegar à plataforma.|Every listed plant goes through technical, economic and regulatory due diligence before reaching the platform.|Cada planta publicada pasa por un análisis técnico, económico y regulatorio antes de llegar a la plataforma.|Chaque centrale publiée fait l’objet d’une analyse technique, économique et réglementaire avant d’arriver sur la plateforme.|Jeder Park durchläuft vor der Veröffentlichung eine technische, wirtschaftliche und regulatorische Prüfung.|每座上线电站都经过技术、经济和监管尽职调查。|掲載する発電所はすべて、技術・経済・規制面の調査を経ています。
about.values|Nossos valores|Our values|Nuestros valores|Nos valeurs|Unsere Werte|我们的价值观|私たちの価値観
about.v1|Transparência|Transparency|Transparencia|Transparence|Transparenz|透明|透明性
about.v1d|Informações claras e atualizadas: dados abertos, premissas e fontes de cada número.|Clear, up-to-date information: open data, assumptions and sources for every number.|Información clara y actualizada: datos abiertos, supuestos y fuentes de cada número.|Des informations claires et à jour : données ouvertes, hypothèses et sources de chaque chiffre.|Klare, aktuelle Informationen: offene Daten, Annahmen und Quellen zu jeder Zahl.|清晰、及时的信息：每个数字的公开数据、假设和来源。|明確で最新の情報：各数値のオープンデータ・前提・出典。
about.v2|Segurança|Security|Seguridad|Sécurité|Sicherheit|安全|安全性
about.v2d|Parceiros e processos auditados; contratos testados e custódia até o fim da oferta.|Audited partners and processes; tested contracts and custody until the offer closes.|Socios y procesos auditados; contratos probados y custodia hasta el final de la oferta.|Partenaires et processus audités ; contrats testés et dépôt jusqu’à la clôture de l’offre.|Geprüfte Partner und Prozesse; getestete Verträge und Verwahrung bis Angebotsende.|经审计的合作方与流程；经过测试的合约，资金托管至认购结束。|監査済みのパートナーとプロセス、テスト済みのコントラクト、募集終了までの保管。
about.v3|Sustentabilidade|Sustainability|Sostenibilidad|Durabilité|Nachhaltigkeit|可持续|サステナビリティ
about.v3d|Energia limpa para um futuro melhor, com CO₂ evitado medido por usina.|Clean energy for a better future, with avoided CO₂ measured per plant.|Energía limpia para un futuro mejor, con CO₂ evitado medido por planta.|Une énergie propre pour un avenir meilleur, avec le CO₂ évité mesuré par centrale.|Saubere Energie für eine bessere Zukunft, mit vermiedenem CO₂ je Park gemessen.|清洁能源创造更好的未来，按电站计量减排的 CO₂。|より良い未来のためのクリーンエネルギー。発電所ごとに CO₂ 削減量を計測。
about.v4|Inovação|Innovation|Innovación|Innovation|Innovation|创新|イノベーション
about.v4d|Tecnologia a favor do seu investimento: cotas digitais e relatórios verificáveis.|Technology working for your investment: digital shares and verifiable reports.|Tecnología a favor de tu inversión: participaciones digitales e informes verificables.|La technologie au service de votre investissement : parts numériques et rapports vérifiables.|Technologie für Ihre Investition: digitale Anteile und überprüfbare Berichte.|技术助力投资：数字份额与可验证报告。|投資のためのテクノロジー：デジタル持分と検証可能なレポート。
about.cta|Junte-se a nós na transição energética.|Join us in the energy transition.|Únete a nosotros en la transición energética.|Rejoignez-nous dans la transition énergétique.|Gestalten Sie mit uns die Energiewende.|与我们一起推动能源转型。|エネルギー転換に一緒に参加しましょう。
about.ctaBtn|Explorar usinas|Explore plants|Explorar plantas|Explorer les centrales|Parks entdecken|浏览电站|発電所を見る
nf.title|Página não encontrada|Page not found|Página no encontrada|Page introuvable|Seite nicht gefunden|页面不存在|ページが見つかりません
nf.text|A usina ou página que você procura não existe.|The plant or page you’re looking for doesn’t exist.|La planta o página que buscas no existe.|La centrale ou la page recherchée n’existe pas.|Der gesuchte Park oder die Seite existiert nicht.|您要找的电站或页面不存在。|お探しの発電所またはページは存在しません。
nf.cta|Ver usinas|See plants|Ver plantas|Voir les centrales|Parks ansehen|查看电站|発電所を見る
err.title|Algo deu errado|Something went wrong|Algo salió mal|Une erreur est survenue|Etwas ist schiefgelaufen|出错了|問題が発生しました
err.text|Não foi possível carregar esta página agora. Tente novamente em instantes.|This page couldn’t load right now. Please try again shortly.|No se pudo cargar esta página ahora. Inténtalo de nuevo en unos instantes.|Impossible de charger cette page pour le moment. Réessayez dans un instant.|Diese Seite konnte gerade nicht geladen werden. Bitte gleich erneut versuchen.|暂时无法加载此页面，请稍后重试。|現在このページを読み込めません。しばらくしてから再試行してください。
err.retry|Tentar de novo|Try again|Intentar de nuevo|Réessayer|Erneut versuchen|重试|再試行
common.ptOnly|Esta página está disponível apenas em português.|This page is currently available in Portuguese only.|Esta página está disponible solo en portugués.|Cette page n’est disponible qu’en portugais.|Diese Seite ist derzeit nur auf Portugiesisch verfügbar.|此页面目前仅提供葡萄牙语版本。|このページは現在ポルトガル語のみです。
"""
