S = r"""
pg.crumb|Trilha|Breadcrumb|Ruta de navegación|Fil d’Ariane|Brotkrumen|面包屑|パンくずリスト
pg.illustrative|Projeto ilustrativo|Illustrative project|Proyecto ilustrativo|Projet illustratif|Beispielprojekt|示例项目|例示プロジェクト
pg.kpiIrr|ao ano (estimado)|per year (estimated)|al año (estimado)|par an (estimé)|pro Jahr (geschätzt)|年化（估算）|年利（推定）
pg.kpiMonthly|por cota, por mês|per share, per month|por participación, al mes|par part, par mois|pro Anteil und Monat|每份每月|1口あたり月額
pg.kpiPayback|para recuperar o valor|to recover the investment|para recuperar la inversión|pour récupérer la mise|bis zur Amortisation|收回投资|投資回収まで
pg.kpiShare|por cota|per share|por participación|par part|pro Anteil|每份|1口あたり
pg.about|Sobre a usina|About the plant|Sobre la planta|À propos de la centrale|Über den Park|电站介绍|発電所について
pg.aboutTpl|{name} é uma usina fotovoltaica de {p} MWp em {city} ({uf}), conectada à rede da {dist}.|{name} is a {p} MWp photovoltaic plant in {city} ({uf}), Brazil, connected to the {dist} grid.|{name} es una planta fotovoltaica de {p} MWp en {city} ({uf}), Brasil, conectada a la red de {dist}.|{name} est une centrale photovoltaïque de {p} MWc à {city} ({uf}), au Brésil, raccordée au réseau de {dist}.|{name} ist eine Photovoltaikanlage mit {p} MWp in {city} ({uf}), Brasilien, angeschlossen an das Netz von {dist}.|{name} 是位于巴西 {city}（{uf}）的 {p} MWp 光伏电站，接入 {dist} 电网。|{name} はブラジル {city}（{uf}）にある {p} MWp の太陽光発電所で、{dist} の送配電網に接続されています。
pg.aboutOp|Em operação desde {d}.|In operation since {d}.|En operación desde {d}.|En exploitation depuis le {d}.|In Betrieb seit {d}.|自 {d} 起投入运营。|{d} から稼働しています。
pg.aboutBuild|Início da operação previsto para {d}; a captação financia a obra.|Commercial operation expected {d}; the raise funds construction.|Inicio de operación previsto para {d}; la captación financia la obra.|Mise en service prévue le {d} ; la levée finance les travaux.|Inbetriebnahme geplant für {d}; die Mittel finanzieren den Bau.|预计 {d} 投运，募集资金用于建设。|{d} 運転開始予定。調達資金で建設します。
pg.aboutPpa|A energia é vendida por contrato de longo prazo (PPA){cp}.|Energy is sold under a long-term power purchase agreement (PPA){cp}.|La energía se vende mediante un contrato de largo plazo (PPA){cp}.|L’électricité est vendue via un contrat d’achat à long terme (PPA){cp}.|Der Strom wird über einen langfristigen Abnahmevertrag (PPA) verkauft{cp}.|电力通过长期购电协议 (PPA) 出售{cp}。|電力は長期電力購入契約 (PPA) で販売されます{cp}。
pg.aboutPpaWith| com {c}| with {c}| con {c}| avec {c}| mit {c}|，购电方为 {c}|（契約先：{c}）
pg.f.local|Local|Location|Ubicación|Emplacement|Standort|地点|所在地
pg.f.power|Potência|Capacity|Potencia|Puissance|Leistung|装机容量|出力
pg.f.ppa|Contrato de energia|Power contract|Contrato de energía|Contrat d’électricité|Stromvertrag|购电协议|電力契約
pg.f.ppaOn|PPA ativo|Active PPA|PPA activo|PPA actif|Aktiver PPA|PPA 生效中|PPA 締結済み
pg.f.ppaOff|Sem PPA ativo|No active PPA|Sin PPA activo|Sans PPA actif|Kein aktiver PPA|无生效 PPA|PPA なし
pg.f.price|Preço do ativo|Asset price|Precio del activo|Prix de l’actif|Preis der Anlage|资产价格|資産価格
pg.f.equip|Equipamentos|Equipment|Equipos|Équipements|Ausrüstung|设备|設備
pg.f.equipTpl|{n} módulos {wp} Wp · {m}|{n} modules {wp} Wp · {m}|{n} módulos {wp} Wp · {m}|{n} modules {wp} Wc · {m}|{n} Module {wp} Wp · {m}|{n} 块 {wp} Wp 组件 · {m}|{wp} Wp モジュール {n} 枚 · {m}
pg.f.fixed|estrutura fixa|fixed-tilt structure|estructura fija|structure fixe|feste Aufständerung|固定支架|固定架台
pg.f.tracker|seguidor solar|solar tracker|seguidor solar|tracker solaire|Solar-Tracker|跟踪支架|追尾架台
pg.f.start|Início da operação|Start of operation|Inicio de operación|Mise en service|Inbetriebnahme|投运日期|運転開始日
pg.scale.micro|Microgeração|Micro-generation|Microgeneración|Micro-production|Mikroerzeugung|微型发电|マイクロ発電
pg.scale.mini|Minigeração|Mini-generation (distributed)|Minigeneración|Mini-production|Minierzeugung|小型分布式发电|ミニ発電（分散型）
pg.scale.large|Grande porte|Utility-scale|Gran escala|Grande échelle|Großanlage|大型电站|大規模
pg.genAria|Geração de energia|Energy generation|Generación de energía|Production d’énergie|Energieerzeugung|发电量|発電量
pg.docs|Documentos|Documents|Documentos|Documents|Dokumente|文件|書類
pg.doc1|Relatório para o investidor|Investor report|Informe para el inversor|Rapport investisseur|Anlegerbericht|投资者报告|投資家向けレポート
pg.doc1m|PDF · 4 páginas · investimento × Selic · em português|PDF · 4 pages · investment vs Selic rate · in Portuguese|PDF · 4 páginas · inversión vs Selic · en portugués|PDF · 4 pages · investissement vs Selic · en portugais|PDF · 4 Seiten · Investition vs. Selic · auf Portugiesisch|PDF · 4 页 · 投资 vs Selic 利率 · 葡萄牙语|PDF · 4 ページ · 投資 vs Selic 金利 · ポルトガル語
pg.doc1mPt|PDF · 4 páginas · investimento × Selic|PDF · 4 pages · investment vs Selic rate|PDF · 4 páginas · inversión vs Selic|PDF · 4 pages · investissement vs Selic|PDF · 4 Seiten · Investition vs. Selic|PDF · 4 页 · 投资 vs Selic 利率|PDF · 4 ページ · 投資 vs Selic 金利
pg.doc2|Relatório de auditoria completo|Full audit report|Informe de auditoría completo|Rapport d’audit complet|Vollständiger Prüfbericht|完整审计报告|完全版監査レポート
pg.doc2m|PDF · geração, economia, riscos e fontes|PDF · generation, economics, risks and sources|PDF · generación, economía, riesgos y fuentes|PDF · production, économie, risques et sources|PDF · Erzeugung, Wirtschaftlichkeit, Risiken und Quellen|PDF · 发电、经济性、风险与数据来源|PDF · 発電・経済性・リスク・出典
pg.doc3|Dados da análise (JSON)|Analysis data (JSON)|Datos del análisis (JSON)|Données de l’analyse (JSON)|Analysedaten (JSON)|分析数据 (JSON)|分析データ (JSON)
pg.download|Baixar|Download|Descargar|Télécharger|Herunterladen|下载|ダウンロード
pg.full|Ver análise completa|See full analysis|Ver análisis completo|Voir l’analyse complète|Vollständige Analyse ansehen|查看完整分析|詳細分析を見る
pg.fullPtNote|A análise técnica detalhada está disponível em português.|The detailed technical analysis is available in Portuguese.|El análisis técnico detallado está disponible en portugués.|L’analyse technique détaillée est disponible en portugais.|Die detaillierte technische Analyse ist auf Portugiesisch verfügbar.|详细技术分析仅提供葡萄牙语版本。|詳細な技術分析はポルトガル語のみで提供しています。
pg.tab.desempenho|Retorno e geração|Returns and generation|Retorno y generación|Rendement et production|Rendite und Erzeugung|收益与发电|収益と発電
pg.tab.riscos|Riscos e condições|Risks and terms|Riesgos y condiciones|Risques et conditions|Risiken und Bedingungen|风险与条款|リスクと条件
pg.tab.tecnico|Dados técnicos|Technical data|Datos técnicos|Données techniques|Technische Daten|技术数据|技術データ
pg.tab.transparencia|Transparência|Transparency|Transparencia|Transparence|Transparenz|透明度|透明性
inv.meta|Investir — {name}|Invest — {name}|Invertir — {name}|Investir — {name}|Investieren — {name}|投资 — {name}|投資 — {name}
inv.crumb|Investir|Invest|Invertir|Investir|Investieren|投资|投資
inv.h1|Investir na {name}|Invest in {name}|Invertir en {name}|Investir dans {name}|In {name} investieren|投资 {name}|{name} に投資
inv.sub|Cota de {c} · distribuição média de {m}/cota/mês · rentabilidade estimada {r} a.a.|Share price {c} · average distribution {m}/share/month · estimated return {r} p.a.|Participación de {c} · distribución media de {m}/participación/mes · rentabilidad estimada {r} anual|Part à {c} · distribution moyenne de {m}/part/mois · rendement estimé {r} par an|Anteil zu {c} · durchschnittliche Ausschüttung {m}/Anteil/Monat · geschätzte Rendite {r} p. a.|每份 {c} · 平均分配 {m}/份/月 · 预计年化收益 {r}|1口 {c} · 平均分配 {m}/口/月 · 推定利回り 年 {r}
inv.flow|Fluxo de aquisição|How to invest|Proceso de adquisición|Parcours d’acquisition|Ablauf der Investition|认购流程|購入の流れ
inv.before|Antes de investir|Before you invest|Antes de invertir|Avant d’investir|Vor der Investition|投资前须知|投資の前に
inv.reportPdf|Relatório para o investidor (PDF)|Investor report (PDF)|Informe para el inversor (PDF)|Rapport investisseur (PDF)|Anlegerbericht (PDF)|投资者报告 (PDF)|投資家向けレポート (PDF)
inv.risks|Riscos e condições da oferta|Offer risks and terms|Riesgos y condiciones de la oferta|Risques et conditions de l’offre|Risiken und Angebotsbedingungen|认购风险与条款|募集のリスクと条件
inv.period|Oferta de {a} a {b} · meta mínima de {n} cotas.|Offer from {a} to {b} · minimum target {n} shares.|Oferta del {a} al {b} · meta mínima de {n} participaciones.|Offre du {a} au {b} · objectif minimum de {n} parts.|Angebot vom {a} bis {b} · Mindestziel {n} Anteile.|认购期 {a} 至 {b} · 最低目标 {n} 份。|募集期間 {a}〜{b} · 最低目標 {n} 口。
inv.periodTbd|Oferta em período a definir · meta mínima de {n} cotas.|Offer period to be defined · minimum target {n} shares.|Período de oferta por definir · meta mínima de {n} participaciones.|Période d’offre à définir · objectif minimum de {n} parts.|Angebotszeitraum offen · Mindestziel {n} Anteile.|认购期待定 · 最低目标 {n} 份。|募集期間は未定 · 最低目標 {n} 口。
inv.closed|Oferta encerrada|Offer closed|Oferta cerrada|Offre clôturée|Angebot geschlossen|认购已结束|募集終了
inv.closedText|Todas as cotas desta usina foram vendidas. Veja as outras|All shares in this plant have been sold. See the other|Todas las participaciones de esta planta se vendieron. Mira las otras|Toutes les parts de cette centrale ont été vendues. Voir les autres|Alle Anteile dieses Parks sind verkauft. Sehen Sie sich die anderen|该电站的所有份额已售罄。查看其他|この発電所の持分はすべて販売済みです。他の
inv.closedLink|usinas disponíveis|available plants|plantas disponibles|centrales disponibles|verfügbaren Parks an|可投电站|投資可能な発電所を見る
inv.card|Aporte com a sua carteira|Invest with your wallet|Aporte con tu billetera|Investir avec votre portefeuille|Mit Ihrer Wallet investieren|使用钱包投资|ウォレットで投資
inv.cardSub|{s} · BNB Smart Chain · pagamento em USDT|{s} · BNB Smart Chain · paid in USDT|{s} · BNB Smart Chain · pago en USDT|{s} · BNB Smart Chain · paiement en USDT|{s} · BNB Smart Chain · Zahlung in USDT|{s} · BNB 智能链 · 以 USDT 支付|{s} · BNB スマートチェーン · USDT で支払い
inv.talk|Prefere falar com a equipe antes?|Prefer to talk to our team first?|¿Prefieres hablar antes con el equipo?|Vous préférez d’abord parler à l’équipe ?|Lieber zuerst mit dem Team sprechen?|想先与团队沟通？|先にチームと話したいですか？
inv.talkSub|Registre seu interesse e tire dúvidas sem compromisso.|Register your interest and ask questions with no commitment.|Registra tu interés y resuelve dudas sin compromiso.|Enregistrez votre intérêt et posez vos questions sans engagement.|Interesse registrieren und unverbindlich Fragen stellen.|登记意向，无需承诺即可咨询。|関心を登録し、気軽にご質問ください。
ip.state.0|Agendada|Scheduled|Programada|Programmée|Geplant|待开始|予定
ip.state.1|Aberta|Open|Abierta|Ouverte|Offen|进行中|募集中
ip.state.2|Meta atingida|Target reached|Meta alcanzada|Objectif atteint|Ziel erreicht|已达目标|目標達成
ip.state.3|Não atingiu a meta|Target not reached|No alcanzó la meta|Objectif non atteint|Ziel verfehlt|未达目标|目標未達
ip.state.4|Encerrada|Closed|Cerrada|Clôturée|Abgeschlossen|已结束|終了
ip.state.5|Cancelada|Cancelled|Cancelada|Annulée|Storniert|已取消|中止
ip.loading|carregando…|loading…|cargando…|chargement…|wird geladen…|加载中…|読み込み中…
ip.notDeployed|Oferta ainda não implantada na {c}|Offer not yet deployed on {c}|Oferta aún no implementada en {c}|Offre pas encore déployée sur {c}|Angebot noch nicht auf {c} bereitgestellt|认购合约尚未部署到 {c}|{c} にはまだ募集が展開されていません
ip.notDeployedText|Os contratos desta usina ainda não foram publicados nesta rede.|This plant’s contracts have not been published on this network yet.|Los contratos de esta planta aún no se publicaron en esta red.|Les contrats de cette centrale ne sont pas encore publiés sur ce réseau.|Die Verträge dieses Parks sind in diesem Netzwerk noch nicht veröffentlicht.|该电站的合约尚未在此网络发布。|この発電所のコントラクトはまだこのネットワークに公開されていません。
ip.sharePrice|Preço da cota|Share price|Precio de la participación|Prix de la part|Anteilspreis|份额价格|1口価格
ip.estIncome|Renda estimada|Estimated income|Ingreso estimado|Revenu estimé|Geschätztes Einkommen|预计收益|推定収益
ip.perShareMonth|{v}/cota/mês|{v}/share/month|{v}/participación/mes|{v}/part/mois|{v}/Anteil/Monat|{v}/份/月|{v}/口/月
ip.perMonth|≈ {v}/mês|≈ {v}/month|≈ {v}/mes|≈ {v}/mois|≈ {v}/Monat|≈ {v}/月|≈ {v}/月
ip.soldOf|{a} de {b} cotas|{a} of {b} shares|{a} de {b} participaciones|{a} sur {b} parts|{a} von {b} Anteilen|{a} / {b} 份|{a} / {b} 口
ip.soldAria|Cotas vendidas|Shares sold|Participaciones vendidas|Parts vendues|Verkaufte Anteile|已售份额|販売済み口数
ip.softCap|meta mínima|minimum target|meta mínima|objectif minimum|Mindestziel|最低目标|最低目標
ip.softCapN|meta mínima {n}|minimum target {n}|meta mínima {n}|objectif minimum {n}|Mindestziel {n}|最低目标 {n}|最低目標 {n}
ip.reserve|Sua reserva|Your reservation|Tu reserva|Votre réservation|Ihre Reservierung|您的认购|あなたの予約
ip.reserveV|{n} cotas · {v}|{n} shares · {v}|{n} participaciones · {v}|{n} parts · {v}|{n} Anteile · {v}|{n} 份 · {v}|{n} 口 · {v}
ip.inWallet|Cotas na carteira|Shares in wallet|Participaciones en la billetera|Parts dans le portefeuille|Anteile in der Wallet|钱包中的份额|ウォレット内の口数
ip.withdrawText|Direito de desistência: {n} cotas dos aportes dos últimos 5 dias ({v}) podem ser devolvidas até {d}.|Cooling-off right: {n} shares from investments in the last 5 days ({v}) can be returned until {d}.|Derecho de desistimiento: {n} participaciones de los aportes de los últimos 5 días ({v}) pueden devolverse hasta {d}.|Droit de rétractation : {n} parts des apports des 5 derniers jours ({v}) peuvent être restituées jusqu’au {d}.|Widerrufsrecht: {n} Anteile aus Einzahlungen der letzten 5 Tage ({v}) können bis {d} zurückgegeben werden.|撤回权：最近 5 天内投资的 {n} 份（{v}）可在 {d} 前退回。|撤回権：直近 5 日間の投資分 {n} 口（{v}）は {d} まで返金できます。
ip.withdrawOlder| Aportes mais antigos já estão firmes na custódia.| Older investments are already locked in custody.| Los aportes más antiguos ya están firmes en custodia.| Les apports plus anciens sont déjà fermes en dépôt.| Ältere Einzahlungen sind bereits fest verwahrt.| 更早的投资已锁定托管。| それ以前の投資はすでに確定しています。
ip.withdrawNoRe| Ao desistir, esta carteira não poderá aportar de novo nesta oferta.| If you withdraw, this wallet cannot invest in this offer again.| Al desistir, esta billetera no podrá aportar de nuevo en esta oferta.| En cas de rétractation, ce portefeuille ne pourra plus investir dans cette offre.| Nach dem Widerruf kann diese Wallet nicht erneut in dieses Angebot investieren.| 撤回后，该钱包不能再次参与本次认购。| 撤回すると、このウォレットでは本募集に再投資できません。
ip.withdrawBtn|Desistir e receber {v}|Withdraw and receive {v}|Desistir y recibir {v}|Se rétracter et recevoir {v}|Widerrufen und {v} erhalten|撤回并取回 {v}|撤回して {v} を受け取る
ip.claimBtn|Receber minhas {n} cotas|Claim my {n} shares|Recibir mis {n} participaciones|Recevoir mes {n} parts|Meine {n} Anteile abholen|领取我的 {n} 份|{n} 口を受け取る
ip.refundBtn|Resgatar reembolso de {v}|Claim refund of {v}|Rescatar reembolso de {v}|Récupérer le remboursement de {v}|Rückerstattung von {v} abholen|领取退款 {v}|{v} の返金を受け取る
ip.opensAt|A oferta abre em {d}.|The offer opens on {d}.|La oferta abre el {d}.|L’offre ouvre le {d}.|Das Angebot öffnet am {d}.|认购将于 {d} 开始。|募集開始は {d} です。
ip.withdrew|Você desistiu desta oferta|You withdrew from this offer|Desististe de esta oferta|Vous vous êtes rétracté de cette offre|Sie haben dieses Angebot widerrufen|您已撤回本次认购|この募集から撤回しました
ip.withdrewText|Para evitar que o teto da captação seja bloqueado por reservas que desistem no fim, uma carteira que exerceu a desistência não pode aportar de novo nesta oferta.|To prevent the raise cap from being blocked by last-minute withdrawals, a wallet that has withdrawn cannot invest in this offer again.|Para evitar que el tope de captación se bloquee con reservas que desisten al final, una billetera que ejerció el desistimiento no puede aportar de nuevo en esta oferta.|Pour éviter que le plafond de la levée soit bloqué par des rétractations de dernière minute, un portefeuille rétracté ne peut plus investir dans cette offre.|Damit die Obergrenze nicht durch kurzfristige Widerrufe blockiert wird, kann eine Wallet nach einem Widerruf nicht erneut investieren.|为避免募集上限被临近结束的撤回占用，已撤回的钱包不能再次参与本次认购。|募集上限が直前の撤回でふさがれるのを防ぐため、撤回したウォレットは本募集に再投資できません。
ip.kycTitle|Verificação de identidade necessária|Identity verification required|Verificación de identidad necesaria|Vérification d’identité requise|Identitätsprüfung erforderlich|需要身份验证|本人確認が必要です
ip.kycText|Só carteiras com KYC aprovado podem investir.|Only wallets with approved KYC can invest.|Solo billeteras con KYC aprobado pueden invertir.|Seuls les portefeuilles avec KYC approuvé peuvent investir.|Nur Wallets mit genehmigtem KYC können investieren.|仅通过 KYC 的钱包可以投资。|KYC 承認済みのウォレットのみ投資できます。
ip.kycLink|Fazer KYC|Complete KYC|Hacer KYC|Faire le KYC|KYC durchführen|完成 KYC|KYC を行う
ip.cotasLabel|Cotas (mín. {min}{max})|Shares (min. {min}{max})|Participaciones (mín. {min}{max})|Parts (min. {min}{max})|Anteile (min. {min}{max})|份额（最少 {min}{max}）|口数（最小 {min}{max}）
ip.cotasMax|, máx. {n} por investidor|, max. {n} per investor|, máx. {n} por inversor|, max. {n} par investisseur|, max. {n} pro Anleger|，每位投资者最多 {n}|、1 人あたり最大 {n}
ip.total|Total|Total|Total|Total|Gesamt|合计|合計
ip.equiv|Equivalente|Equivalent|Equivalente|Équivalent|Entspricht|折合|相当額
ip.balance|Seu saldo|Your balance|Tu saldo|Votre solde|Ihr Guthaben|您的余额|残高
ip.faucet|Pegar USDT de teste (faucet)|Get test USDT (faucet)|Obtener USDT de prueba (faucet)|Obtenir des USDT de test (faucet)|Test-USDT holen (Faucet)|领取测试 USDT（水龙头）|テスト用 USDT を受け取る（フォーセット）
ip.step1|Passo 1 de 2: autorize exatamente {v} para o contrato da oferta|Step 1 of 2: approve exactly {v} for the offer contract|Paso 1 de 2: autoriza exactamente {v} para el contrato de la oferta|Étape 1 sur 2 : autorisez exactement {v} pour le contrat de l’offre|Schritt 1 von 2: genau {v} für den Angebotsvertrag freigeben|第 1/2 步：为认购合约授权恰好 {v}|ステップ 1/2：募集コントラクトに正確に {v} を承認
ip.noUnlimited|. Nunca pedimos aprovação ilimitada.|. We never ask for unlimited approval.|. Nunca pedimos aprobación ilimitada.|. Nous ne demandons jamais d’autorisation illimitée.|. Wir verlangen nie eine unbegrenzte Freigabe.|。我们绝不会请求无限额授权。|。無制限の承認は決して求めません。
ip.approve|Aprovar {v}|Approve {v}|Aprobar {v}|Approuver {v}|{v} freigeben|授权 {v}|{v} を承認
ip.step2|Passo 2 de 2: |Step 2 of 2: |Paso 2 de 2: |Étape 2 sur 2 : |Schritt 2 von 2: |第 2/2 步：|ステップ 2/2：
ip.investN|Investir em {n} cotas|Invest in {n} shares|Invertir en {n} participaciones|Investir dans {n} parts|In {n} Anteile investieren|投资 {n} 份|{n} 口に投資
ip.custody|O valor fica em custódia no contrato. Cada aporte tem 5 dias próprios para desistência (um novo aporte não reabre os anteriores); se a meta mínima não for atingida, tudo é devolvido.|Funds are held in custody by the contract. Each investment has its own 5-day cooling-off period (a new one doesn’t reopen earlier ones); if the minimum target isn’t reached, everything is refunded.|El valor queda en custodia en el contrato. Cada aporte tiene 5 días propios para desistir (un nuevo aporte no reabre los anteriores); si no se alcanza la meta mínima, se devuelve todo.|Les fonds restent en dépôt dans le contrat. Chaque apport a son propre délai de rétractation de 5 jours (un nouvel apport ne rouvre pas les précédents) ; si l’objectif minimum n’est pas atteint, tout est remboursé.|Das Geld wird vom Vertrag verwahrt. Jede Einzahlung hat eine eigene 5-Tage-Widerrufsfrist (eine neue öffnet frühere nicht erneut); wird das Mindestziel verfehlt, wird alles erstattet.|资金由合约托管。每笔投资各有 5 天撤回期（新投资不会重新开启之前的撤回期）；若未达最低目标，全额退还。|資金はコントラクトで保管されます。各投資に 5 日間の撤回期間があり（新たな投資で以前の期間は再開しません）、最低目標に届かない場合は全額返金されます。
ip.reached|Meta atingida! A oferta será encerrada após o prazo de desistência e as cotas serão entregues.|Target reached! The offer will close after the cooling-off period and shares will be delivered.|¡Meta alcanzada! La oferta se cerrará tras el plazo de desistimiento y se entregarán las participaciones.|Objectif atteint ! L’offre sera clôturée après le délai de rétractation et les parts livrées.|Ziel erreicht! Das Angebot schließt nach der Widerrufsfrist, dann werden die Anteile geliefert.|已达目标！撤回期结束后认购将关闭并交付份额。|目標達成！撤回期間の終了後に募集を締め切り、持分をお渡しします。
ip.closedIn|Oferta encerrada. Cotas e rendimentos na|Offer closed. Shares and income in|Oferta cerrada. Participaciones y rendimientos en|Offre clôturée. Parts et revenus dans|Angebot geschlossen. Anteile und Erträge in|认购已结束。份额与收益见|募集終了。持分と収益は
ip.yourWallet|sua carteira|your wallet|tu billetera|votre portefeuille|Ihrer Wallet|您的钱包|あなたのウォレットへ
ip.failed|A oferta não foi concluída (meta mínima não atingida ou encerramento fora do prazo).|The offer was not completed (minimum target not reached or not closed in time).|La oferta no se concluyó (meta mínima no alcanzada o cierre fuera de plazo).|L’offre n’a pas abouti (objectif minimum non atteint ou clôture hors délai).|Das Angebot kam nicht zustande (Mindestziel verfehlt oder nicht fristgerecht abgeschlossen).|认购未完成（未达最低目标或未按时结束）。|募集は成立しませんでした（最低目標未達、または期限内に終了せず）。
ip.cancelled|A oferta foi cancelada.|The offer was cancelled.|La oferta fue cancelada.|L’offre a été annulée.|Das Angebot wurde storniert.|认购已取消。|募集は中止されました。
ip.refundAll| Quem investiu pode resgatar 100% do valor.| Investors can reclaim 100% of the amount.| Quien invirtió puede rescatar el 100% del valor.| Les investisseurs peuvent récupérer 100 % du montant.| Anleger können 100 % zurückfordern.| 投资者可取回 100% 金额。| 投資家は全額を取り戻せます。
ip.viewTx|ver transação {h}|view transaction {h}|ver transacción {h}|voir la transaction {h}|Transaktion {h} ansehen|查看交易 {h}|取引 {h} を表示
ip.lbl.withdraw|Desistência|Withdrawal|Desistimiento|Rétractation|Widerruf|撤回|撤回
ip.lbl.claim|Recebimento das cotas|Share delivery|Recepción de participaciones|Réception des parts|Anteilsübergabe|领取份额|持分の受け取り
ip.lbl.refund|Reembolso|Refund|Reembolso|Remboursement|Rückerstattung|退款|返金
ip.lbl.faucet|Faucet de USDT de teste|Test USDT faucet|Faucet de USDT de prueba|Faucet USDT de test|Test-USDT-Faucet|测试 USDT 水龙头|テスト用 USDT フォーセット
ip.lbl.approve|Aprovação de USDT|USDT approval|Aprobación de USDT|Autorisation USDT|USDT-Freigabe|USDT 授权|USDT 承認
ip.lbl.invest|Investimento|Investment|Inversión|Investissement|Investition|投资|投資
tx.switching|Trocando de rede na carteira…|Switching network in your wallet…|Cambiando de red en la billetera…|Changement de réseau dans le portefeuille…|Netzwerk in der Wallet wird gewechselt…|正在钱包中切换网络…|ウォレットでネットワークを切り替え中…
tx.simulating|Simulando a transação…|Simulating the transaction…|Simulando la transacción…|Simulation de la transaction…|Transaktion wird simuliert…|正在模拟交易…|取引をシミュレーション中…
tx.signing|Confirme na sua carteira…|Confirm in your wallet…|Confirma en tu billetera…|Confirmez dans votre portefeuille…|In Ihrer Wallet bestätigen…|请在钱包中确认…|ウォレットで承認してください…
tx.pending|Aguardando confirmação na BNB Chain…|Waiting for confirmation on BNB Chain…|Esperando confirmación en BNB Chain…|En attente de confirmation sur BNB Chain…|Warten auf Bestätigung in der BNB Chain…|等待 BNB Chain 确认…|BNB Chain での承認を待っています…
tx.done|Concluído|Done|Completado|Terminé|Erledigt|已完成|完了
tx.cancelled|Você cancelou a assinatura na carteira.|You cancelled the signature in your wallet.|Cancelaste la firma en la billetera.|Vous avez annulé la signature dans le portefeuille.|Sie haben die Signatur in der Wallet abgebrochen.|您已在钱包中取消签名。|ウォレットで署名をキャンセルしました。
tx.reverted|A transação foi revertida na rede.|The transaction was reverted on the network.|La transacción fue revertida en la red.|La transaction a été annulée sur le réseau.|Die Transaktion wurde im Netzwerk rückgängig gemacht.|交易在链上被回滚。|取引はネットワーク上で取り消されました。
tx.refused|O contrato recusou a operação ({n}).|The contract rejected the operation ({n}).|El contrato rechazó la operación ({n}).|Le contrat a refusé l’opération ({n}).|Der Vertrag hat den Vorgang abgelehnt ({n}).|合约拒绝了此操作（{n}）。|コントラクトが操作を拒否しました（{n}）。
tx.gas|Saldo de BNB insuficiente para pagar o gás.|Not enough BNB to pay for gas.|Saldo de BNB insuficiente para pagar el gas.|Solde BNB insuffisant pour payer le gaz.|Nicht genug BNB für die Gasgebühr.|BNB 余额不足以支付 Gas。|ガス代の BNB が不足しています。
tx.generic|Não foi possível concluir a operação.|The operation could not be completed.|No se pudo completar la operación.|L’opération n’a pas pu aboutir.|Der Vorgang konnte nicht abgeschlossen werden.|无法完成该操作。|操作を完了できませんでした。
tx.e.NotVerified|Carteira sem KYC válido no registro de investidores.|Wallet has no valid KYC in the investor registry.|Billetera sin KYC válido en el registro de inversores.|Portefeuille sans KYC valide au registre des investisseurs.|Wallet ohne gültiges KYC im Anlegerregister.|该钱包在投资者登记中无有效 KYC。|投資家登録に有効な KYC がないウォレットです。
tx.e.InvalidState|A oferta não está na fase certa para esta operação.|The offer is not in the right phase for this operation.|La oferta no está en la fase correcta para esta operación.|L’offre n’est pas dans la bonne phase pour cette opération.|Das Angebot ist nicht in der richtigen Phase.|认购不处于可执行此操作的阶段。|募集がこの操作を行える段階ではありません。
tx.e.BelowMinimum|Quantidade abaixo do mínimo por aporte.|Amount below the minimum per investment.|Cantidad por debajo del mínimo por aporte.|Quantité inférieure au minimum par apport.|Menge unter dem Mindestbetrag pro Einzahlung.|低于每笔最低投资数量。|1 回あたりの最低口数を下回っています。
tx.e.ExceedsInvestorCap|Acima do limite de cotas por investidor.|Above the per-investor share limit.|Por encima del límite de participaciones por inversor.|Au-delà de la limite de parts par investisseur.|Über dem Anteilslimit pro Anleger.|超过每位投资者的份额上限。|1 人あたりの上限口数を超えています。
tx.e.ExceedsHardCap|Não há cotas suficientes disponíveis na oferta.|Not enough shares available in the offer.|No hay suficientes participaciones disponibles en la oferta.|Pas assez de parts disponibles dans l’offre.|Nicht genügend Anteile im Angebot verfügbar.|可认购份额不足。|募集の残り口数が不足しています。
tx.e.TransferAmountMismatch|Token de pagamento incompatível (taxa na transferência).|Incompatible payment token (transfer fee).|Token de pago incompatible (comisión en la transferencia).|Jeton de paiement incompatible (frais de transfert).|Inkompatibler Zahlungs-Token (Transfergebühr).|支付代币不兼容（转账收费）。|支払いトークンが非対応です（送金手数料）。
tx.e.NoCommitment|Você não tem aporte nesta oferta.|You have no investment in this offer.|No tienes aporte en esta oferta.|Vous n’avez pas d’apport dans cette offre.|Sie haben in diesem Angebot nicht investiert.|您在本次认购中没有投资。|この募集への投資はありません。
tx.e.RecommitAfterWithdrawal|Você desistiu desta oferta e não pode aportar novamente nela.|You withdrew from this offer and cannot invest in it again.|Desististe de esta oferta y no puedes aportar de nuevo.|Vous vous êtes rétracté et ne pouvez plus investir dans cette offre.|Sie haben widerrufen und können nicht erneut investieren.|您已撤回，不能再次参与本次认购。|撤回済みのため再投資できません。
tx.e.WithdrawalWindowClosed|O prazo de desistência (5 dias) já passou.|The 5-day cooling-off period has ended.|El plazo de desistimiento (5 días) ya pasó.|Le délai de rétractation (5 jours) est écoulé.|Die 5-tägige Widerrufsfrist ist abgelaufen.|5 天撤回期已过。|5 日間の撤回期間は終了しました。
tx.e.WithdrawalPeriodOpen|Ainda há prazo de desistência aberto; o encerramento só ocorre depois dele.|A cooling-off period is still open; closing happens only after it.|Aún hay plazo de desistimiento abierto; el cierre ocurre después.|Un délai de rétractation est encore ouvert ; la clôture intervient après.|Eine Widerrufsfrist läuft noch; der Abschluss erfolgt danach.|仍有撤回期未结束，之后才能关闭。|撤回期間中のため、終了はその後になります。
tx.e.NothingToRefund|Não há valor a ser devolvido.|There is nothing to refund.|No hay valor a devolver.|Rien à rembourser.|Nichts zu erstatten.|没有可退还的金额。|返金対象はありません。
tx.e.NotFinalized|A oferta ainda não foi encerrada.|The offer has not been closed yet.|La oferta aún no se cerró.|L’offre n’est pas encore clôturée.|Das Angebot ist noch nicht abgeschlossen.|认购尚未结束。|募集はまだ終了していません。
tx.e.AlreadySettled|Suas cotas já foram entregues.|Your shares have already been delivered.|Tus participaciones ya fueron entregadas.|Vos parts ont déjà été livrées.|Ihre Anteile wurden bereits geliefert.|您的份额已交付。|持分はすでにお渡し済みです。
tx.e.MaxSupplyExceeded|Limite de cotas da usina atingido.|The plant’s share limit has been reached.|Se alcanzó el límite de participaciones de la planta.|Limite de parts de la centrale atteinte.|Anteilslimit des Parks erreicht.|已达电站份额上限。|発電所の上限口数に達しました。
tx.e.MintingNotFinished|A distribuição só começa após a entrega de todas as cotas.|Distributions start only after all shares are delivered.|La distribución solo comienza tras la entrega de todas las participaciones.|Les distributions ne commencent qu’après la livraison de toutes les parts.|Ausschüttungen beginnen erst nach Lieferung aller Anteile.|所有份额交付后才开始分配。|全持分の引き渡し後に分配が始まります。
tx.e.NothingToClaim|Não há rendimento disponível para resgate.|No income available to claim.|No hay rendimiento disponible para rescatar.|Aucun revenu disponible.|Keine Erträge zum Abholen.|暂无可领取的收益。|受け取れる収益はありません。
tx.e.FaucetCooldown|Faucet já usado hoje — tente novamente mais tarde.|Faucet already used today — try again later.|Faucet ya usado hoy — inténtalo más tarde.|Faucet déjà utilisé aujourd’hui — réessayez plus tard.|Faucet heute schon genutzt — später erneut versuchen.|今日已使用过水龙头，请稍后再试。|本日はフォーセット使用済みです。後でお試しください。
tx.e.FaucetCapReached|Limite do faucet de teste atingido para esta carteira.|Test faucet limit reached for this wallet.|Límite del faucet de prueba alcanzado para esta billetera.|Limite du faucet de test atteinte pour ce portefeuille.|Test-Faucet-Limit für diese Wallet erreicht.|该钱包已达测试水龙头上限。|このウォレットはテスト用フォーセットの上限に達しました。
tx.e.EnforcedPause|Operação pausada temporariamente pelo administrador.|Operation temporarily paused by the administrator.|Operación pausada temporalmente por el administrador.|Opération suspendue temporairement par l’administrateur.|Vorgang vom Administrator vorübergehend pausiert.|管理员已暂停该操作。|管理者により一時停止中です。
tx.e.ERC20InsufficientBalance|Saldo de USDT insuficiente.|Insufficient USDT balance.|Saldo de USDT insuficiente.|Solde USDT insuffisant.|USDT-Guthaben nicht ausreichend.|USDT 余额不足。|USDT 残高が不足しています。
tx.e.ERC20InsufficientAllowance|Aprovação de USDT insuficiente — aprove o valor antes.|Insufficient USDT approval — approve the amount first.|Aprobación de USDT insuficiente — aprueba el valor antes.|Autorisation USDT insuffisante — approuvez d’abord le montant.|USDT-Freigabe zu gering — zuerst Betrag freigeben.|USDT 授权不足，请先授权金额。|USDT の承認額が不足しています。先に承認してください。
tx.e.AccessControlUnauthorizedAccount|Esta carteira não tem permissão para esta operação.|This wallet is not allowed to perform this operation.|Esta billetera no tiene permiso para esta operación.|Ce portefeuille n’est pas autorisé à effectuer cette opération.|Diese Wallet ist für den Vorgang nicht berechtigt.|该钱包无权执行此操作。|このウォレットにはこの操作の権限がありません。
"""
