S = r"""
sim.title|Simulador de investimento|Investment simulator|Simulador de inversión|Simulateur d’investissement|Investitionsrechner|投资模拟器|投資シミュレーター
sim.sub|Faça uma estimativa de quanto você pode receber com base na quantidade de cotas escolhida.|Estimate how much you could receive based on the number of shares you choose.|Calcula cuánto podrías recibir según la cantidad de participaciones elegida.|Estimez ce que vous pourriez recevoir selon le nombre de parts choisi.|Schätzen Sie, wie viel Sie je nach Anzahl der Anteile erhalten könnten.|根据所选份额数量估算您可能获得的收益。|選んだ口数に応じて受け取れる金額を試算します。
sim.plant|Usina|Plant|Planta|Centrale|Park|电站|発電所
sim.pricePerShare|Valor por cota|Price per share|Valor por participación|Prix par part|Preis pro Anteil|每份价格|1口あたりの価格
sim.monthlyPerShare|Distribuição mensal (por cota)|Monthly distribution (per share)|Distribución mensual (por participación)|Distribution mensuelle (par part)|Monatliche Ausschüttung (pro Anteil)|月度分配（每份）|月間分配（1口あたり）
sim.qty|Quantidade de cotas|Number of shares|Cantidad de participaciones|Nombre de parts|Anzahl der Anteile|份额数量|口数
sim.total|Investimento total|Total investment|Inversión total|Investissement total|Gesamtinvestition|投资总额|投資総額
sim.monthlyEst|Distribuição mensal estimada|Estimated monthly distribution|Distribución mensual estimada|Distribution mensuelle estimée|Geschätzte monatliche Ausschüttung|预计月度分配|推定月間分配
sim.annual|Rentabilidade anual (estimada)|Annual return (estimated)|Rentabilidad anual (estimada)|Rendement annuel (estimé)|Jahresrendite (geschätzt)|年化收益（估算）|年間利回り（推定）
sim.pa|{v} a.a.|{v} p.a.|{v} anual|{v} par an|{v} p. a.|年化 {v}|年 {v}
sim.selic|Selic hoje|Brazil’s Selic rate today|Tasa Selic hoy|Taux Selic aujourd’hui|Selic-Leitzins heute|巴西 Selic 基准利率|現在の Selic 金利
sim.run|Simular|Simulate|Simular|Simuler|Berechnen|模拟|試算する
sim.scenarios|Cenários (estimativos)|Scenarios (estimates)|Escenarios (estimados)|Scénarios (estimations)|Szenarien (Schätzungen)|情景（估算）|シナリオ（推定）
sim.sc.conservador|Conservador|Conservative|Conservador|Prudent|Konservativ|保守|保守的
sim.sc.base|Base|Base|Base|Central|Basis|基准|ベース
sim.sc.otimista|Otimista|Optimistic|Optimista|Optimiste|Optimistisch|乐观|楽観的
sim.hint.conservador|geração P90|P90 generation|generación P90|production P90|Erzeugung P90|P90 发电量|P90 発電量
sim.hint.base|geração P50|P50 generation|generación P50|production P50|Erzeugung P50|P50 发电量|P50 発電量
sim.hint.otimista|geração acima do P50|above-P50 generation|generación por encima del P50|production supérieure au P50|Erzeugung über P50|高于 P50 的发电量|P50 超の発電量
sim.perMonth|{v}/mês|{v}/month|{v}/mes|{v}/mois|{v}/Monat|{v}/月|{v}/月
sim.disclaimer|Os cenários apresentados são estimativas e não representam garantia de retorno. Valores médios mensais ao longo do prazo, antes de impostos do investidor.|Scenarios are estimates and do not guarantee returns. Monthly averages over the full term, before investor taxes.|Los escenarios son estimaciones y no garantizan retorno. Promedios mensuales a lo largo del plazo, antes de impuestos del inversor.|Les scénarios sont des estimations et ne garantissent aucun rendement. Moyennes mensuelles sur toute la durée, avant impôts de l’investisseur.|Die Szenarien sind Schätzungen und keine Renditegarantie. Monatliche Durchschnittswerte über die Laufzeit, vor Steuern des Anlegers.|情景为估算，不构成收益保证。为整个期限内的月均值，未扣除投资者税费。|シナリオは推定であり、収益を保証するものではありません。期間全体の月平均、投資家の税引前の値です。
sim.chartTitle|Renda acumulada × valor investido|Cumulative income vs amount invested|Ingreso acumulado vs valor invertido|Revenu cumulé vs montant investi|Kumuliertes Einkommen vs. Investition|累计收益 vs 投资金额|累計収益と投資額
sim.chartMeta|{n} cotas · {v} em {y} anos|{n} shares · {v} over {y} years|{n} participaciones · {v} en {y} años|{n} parts · {v} sur {y} ans|{n} Anteile · {v} in {y} Jahren|{n} 份 · {y} 年合计 {v}|{n} 口 · {y} 年で {v}
sim.chartAria|Renda acumulada por ano comparada ao valor investido|Cumulative income per year compared with the amount invested|Ingreso acumulado por año comparado con el valor invertido|Revenu cumulé par an comparé au montant investi|Kumuliertes Einkommen pro Jahr im Vergleich zur Investition|逐年累计收益与投资金额对比|年ごとの累計収益と投資額の比較
sim.cumulative|Renda acumulada|Cumulative income|Ingreso acumulado|Revenu cumulé|Kumuliertes Einkommen|累计收益|累計収益
sim.invested|Valor investido|Amount invested|Valor invertido|Montant investi|Investierter Betrag|投资金额|投資額
sim.interest|Demonstrar interesse →|Express interest →|Mostrar interés →|Manifester son intérêt →|Interesse bekunden →|表达投资意向 →|関心を登録 →
sim.withWallet|Investir com carteira|Invest with wallet|Invertir con billetera|Investir avec le portefeuille|Mit Wallet investieren|使用钱包投资|ウォレットで投資
pf.meta|Meu portfólio|My portfolio|Mi portafolio|Mon portefeuille|Mein Portfolio|我的投资组合|マイポートフォリオ
pf.area|Área do investidor|Investor area|Área del inversor|Espace investisseur|Anlegerbereich|投资者专区|投資家エリア
pf.nav.portfolio|Meu portfólio|My portfolio|Mi portafolio|Mon portefeuille|Mein Portfolio|我的投资组合|マイポートフォリオ
pf.nav.tx|Transações|Transactions|Transacciones|Transactions|Transaktionen|交易记录|取引履歴
pf.nav.docs|Documentos|Documents|Documentos|Documents|Dokumente|文件|書類
pf.nav.profile|Perfil|Profile|Perfil|Profil|Profil|个人资料|プロフィール
pf.nav.support|Suporte|Support|Soporte|Assistance|Support|支持|サポート
pf.logout|Sair|Sign out|Salir|Se déconnecter|Abmelden|退出|ログアウト
pf.demoName|Investidor (demonstração)|Investor (demo)|Inversor (demostración)|Investisseur (démo)|Anleger (Demo)|投资者（演示）|投資家（デモ）
pf.demoTitle|Demonstração:|Demo:|Demostración:|Démo :|Demo:|演示：|デモ：
pf.demoText|dados fictícios para conhecer o portfólio. Nada aqui é uma posição real.|sample data to explore the portfolio. Nothing here is a real position.|datos ficticios para conocer el portafolio. Nada aquí es una posición real.|données fictives pour découvrir le portefeuille. Rien ici n’est une position réelle.|Beispieldaten zum Kennenlernen des Portfolios. Nichts davon ist eine echte Position.|用于了解投资组合的示例数据，均非真实持仓。|ポートフォリオを体験するための架空データです。実際の保有ではありません。
pf.demoExit|Sair da demonstração|Exit demo|Salir de la demostración|Quitter la démo|Demo beenden|退出演示|デモを終了
pf.signInTitle|Entre com a sua carteira|Sign in with your wallet|Entra con tu billetera|Connectez-vous avec votre portefeuille|Mit Ihrer Wallet anmelden|使用钱包登录|ウォレットでログイン
pf.signInText|Suas cotas, distribuições e documentos ficam registrados na BNB Chain e aparecem aqui quando você conecta a carteira.|Your shares, distributions and documents are recorded on BNB Chain and appear here when you connect your wallet.|Tus participaciones, distribuciones y documentos quedan registrados en BNB Chain y aparecen aquí al conectar la billetera.|Vos parts, distributions et documents sont enregistrés sur BNB Chain et s’affichent ici lorsque vous connectez votre portefeuille.|Ihre Anteile, Ausschüttungen und Dokumente sind auf der BNB Chain gespeichert und erscheinen hier, sobald Sie Ihre Wallet verbinden.|您的份额、分配和文件记录在 BNB Chain 上，连接钱包后即可在此查看。|持分・分配・書類は BNB Chain に記録され、ウォレットを接続するとここに表示されます。
pf.seeDemo|Ver um portfólio de demonstração|View a demo portfolio|Ver un portafolio de demostración|Voir un portefeuille de démonstration|Demo-Portfolio ansehen|查看演示投资组合|デモのポートフォリオを見る
pf.title|Meu portfólio|My portfolio|Mi portafolio|Mon portefeuille|Mein Portfolio|我的投资组合|マイポートフォリオ
pf.sub|Acompanhe seus investimentos e o desempenho da sua carteira.|Track your investments and portfolio performance.|Sigue tus inversiones y el desempeño de tu portafolio.|Suivez vos investissements et la performance de votre portefeuille.|Verfolgen Sie Ihre Investitionen und die Wertentwicklung.|跟踪您的投资及组合表现。|投資とポートフォリオの成績を確認できます。
pf.empty|Você ainda não tem cotas|You don’t have any shares yet|Aún no tienes participaciones|Vous n’avez pas encore de parts|Sie haben noch keine Anteile|您还没有份额|まだ持分がありません
pf.loading|Lendo seus dados na blockchain…|Reading your data on the blockchain…|Leyendo tus datos en la blockchain…|Lecture de vos données sur la blockchain…|Ihre Daten werden aus der Blockchain gelesen…|正在从区块链读取您的数据…|ブロックチェーンからデータを読み込み中…
pf.emptyText|Quando você investir em uma usina, suas cotas, distribuições e documentos aparecem aqui.|When you invest in a plant, your shares, distributions and documents will appear here.|Cuando inviertas en una planta, tus participaciones, distribuciones y documentos aparecerán aquí.|Lorsque vous investirez dans une centrale, vos parts, distributions et documents apparaîtront ici.|Sobald Sie in einen Park investieren, erscheinen hier Ihre Anteile, Ausschüttungen und Dokumente.|投资电站后，您的份额、分配和文件将显示在这里。|発電所に投資すると、持分・分配・書類がここに表示されます。
pf.explore|Explorar usinas|Explore plants|Explorar plantas|Explorer les centrales|Parks entdecken|浏览电站|発電所を見る
pf.demo|Ver demonstração|View demo|Ver demostración|Voir la démo|Demo ansehen|查看演示|デモを見る
pf.kpi.invested|Total investido|Total invested|Total invertido|Total investi|Gesamt investiert|累计投资|投資総額
pf.kpi.cotas|Cotas|Shares|Participaciones|Parts|Anteile|份额|口数
pf.kpi.received|Distribuições recebidas|Distributions received|Distribuciones recibidas|Distributions reçues|Erhaltene Ausschüttungen|已收分配|受取済み分配
pf.kpi.monthly|Distribuição mensal estimada|Estimated monthly distribution|Distribución mensual estimada|Distribution mensuelle estimée|Geschätzte monatliche Ausschüttung|预计月度分配|推定月間分配
pf.byPlant|Distribuição por usina|Allocation by plant|Distribución por planta|Répartition par centrale|Aufteilung nach Park|按电站分布|発電所別の配分
pf.byPlantAria|Distribuição do valor investido por usina|Invested amount by plant|Distribución del valor invertido por planta|Montant investi par centrale|Investierter Betrag nach Park|各电站投资金额分布|発電所別の投資額
pf.distributions|distribuições|distributions|distribuciones|distributions|Ausschüttungen|分配|分配
pf.evolution|Evolução do patrimônio|Portfolio value over time|Evolución del patrimonio|Évolution du patrimoine|Vermögensentwicklung|资产变化|資産の推移
pf.evolutionSub|Valor de face das cotas + distribuições recebidas|Face value of shares + distributions received|Valor nominal de las participaciones + distribuciones recibidas|Valeur nominale des parts + distributions reçues|Nennwert der Anteile + erhaltene Ausschüttungen|份额面值 + 已收分配|持分の額面 + 受取済み分配
pf.evolutionAria|Evolução do patrimônio nos últimos 12 meses|Portfolio value over the last 12 months|Evolución del patrimonio en los últimos 12 meses|Évolution du patrimoine sur les 12 derniers mois|Vermögensentwicklung der letzten 12 Monate|过去 12 个月资产变化|過去 12 か月の資産推移
pf.equity|Patrimônio|Portfolio value|Patrimonio|Patrimoine|Vermögen|资产|資産
pf.positions|Suas posições|Your positions|Tus posiciones|Vos positions|Ihre Positionen|您的持仓|保有状況
pf.claimable|Disponível para resgate: {v}|Available to claim: {v}|Disponible para rescatar: {v}|Disponible à retirer : {v}|Zum Abholen verfügbar: {v}|可领取：{v}|受取可能：{v}
pf.col.plant|Usina|Plant|Planta|Centrale|Park|电站|発電所
pf.col.cotas|Cotas|Shares|Participaciones|Parts|Anteile|份额|口数
pf.col.invested|Valor investido|Amount invested|Valor invertido|Montant investi|Investiert|投资金额|投資額
pf.col.received|Distribuições recebidas|Distributions received|Distribuciones recibidas|Distributions reçues|Erhaltene Ausschüttungen|已收分配|受取済み分配
pf.col.irr|Rentabilidade (a.a.)|Return (p.a.)|Rentabilidad (anual)|Rendement (par an)|Rendite (p. a.)|收益率（年化）|利回り（年）
pf.col.status|Status|Status|Estado|Statut|Status|状态|ステータス
pf.custody| · {n} em custódia| · {n} in custody| · {n} en custodia| · {n} en dépôt| · {n} in Verwahrung| · {n} 份托管中| · {n} 口を保管中
pf.claimLbl|Resgate {name}|Claim {name}|Rescate {name}|Retrait {name}|Abholung {name}|领取 {name}|{name} の受け取り
pf.claimBtn|Resgatar {v}|Claim {v}|Rescatar {v}|Retirer {v}|{v} abholen|领取 {v}|{v} を受け取る
pf.details|Ver detalhes →|View details →|Ver detalles →|Voir le détail →|Details ansehen →|查看详情 →|詳細を見る →
pf.series.note1|Extrato dos últimos ~1,5 dia de blocos; o histórico completo está no BscScan.|Statement covers the last ~1.5 days of blocks; the full history is on BscScan.|Extracto de los últimos ~1,5 días de bloques; el histórico completo está en BscScan.|Relevé des ~1,5 derniers jours de blocs ; l’historique complet est sur BscScan.|Auszug der letzten ~1,5 Tage an Blöcken; der vollständige Verlauf ist auf BscScan.|仅显示最近约 1.5 天的区块记录，完整历史请见 BscScan。|直近約 1.5 日分のブロックの明細です。全履歴は BscScan で確認できます。
pf.series.note2|Não foi possível ler o extrato on-chain agora (limite da RPC pública). Consulte o histórico no BscScan.|Couldn’t read the on-chain statement right now (public RPC limit). Check the history on BscScan.|No se pudo leer el extracto on-chain ahora (límite del RPC público). Consulta el histórico en BscScan.|Impossible de lire le relevé on-chain pour le moment (limite du RPC public). Consultez l’historique sur BscScan.|On-Chain-Auszug derzeit nicht lesbar (Limit des öffentlichen RPC). Verlauf auf BscScan ansehen.|暂时无法读取链上记录（公共 RPC 限制），请在 BscScan 查看历史。|現在オンチェーン明細を読み込めません（公開 RPC の制限）。履歴は BscScan でご確認ください。
txp.title|Transações|Transactions|Transacciones|Transactions|Transaktionen|交易记录|取引履歴
txp.sub|Aportes, distribuições e resgates da sua carteira.|Investments, distributions and claims from your wallet.|Aportes, distribuciones y rescates de tu billetera.|Apports, distributions et retraits de votre portefeuille.|Einzahlungen, Ausschüttungen und Abholungen Ihrer Wallet.|您钱包的投资、分配与领取记录。|ウォレットの投資・分配・受け取りの記録。
txp.all|Todas|All|Todas|Toutes|Alle|全部|すべて
txp.k.aporte|Aporte|Investment|Aporte|Apport|Einzahlung|投资|投資
txp.k.distribuicao|Distribuição|Distribution|Distribución|Distribution|Ausschüttung|分配|分配
txp.k.resgate|Resgate de rendimentos|Income claim|Rescate de rendimientos|Retrait des revenus|Ertragsabholung|领取收益|収益の受け取り
txp.k.desistencia|Desistência (devolução)|Withdrawal (refund)|Desistimiento (devolución)|Rétractation (restitution)|Widerruf (Rückzahlung)|撤回（退款）|撤回（返金）
txp.k.reembolso|Reembolso|Refund|Reembolso|Remboursement|Rückerstattung|退款|返金
txp.k.entrega|Entrega das cotas|Share delivery|Entrega de participaciones|Livraison des parts|Anteilslieferung|份额交付|持分の引き渡し
txp.loading|Lendo eventos na blockchain…|Reading events on the blockchain…|Leyendo eventos en la blockchain…|Lecture des événements sur la blockchain…|Ereignisse werden aus der Blockchain gelesen…|正在读取链上事件…|ブロックチェーンのイベントを読み込み中…
txp.none|Nenhuma transação encontrada.|No transactions found.|No se encontraron transacciones.|Aucune transaction trouvée.|Keine Transaktionen gefunden.|未找到交易记录。|取引はありません。
txp.col.date|Data|Date|Fecha|Date|Datum|日期|日付
txp.col.type|Tipo|Type|Tipo|Type|Art|类型|種類
txp.col.plant|Usina|Plant|Planta|Centrale|Park|电站|発電所
txp.col.cotas|Cotas|Shares|Participaciones|Parts|Anteile|份额|口数
txp.col.amount|Valor|Amount|Valor|Montant|Betrag|金额|金額
txp.col.receipt|Comprovante|Receipt|Comprobante|Justificatif|Beleg|凭证|証跡
txp.demo|demonstração|demo|demostración|démo|Demo|演示|デモ
docp.title|Documentos|Documents|Documentos|Documents|Dokumente|文件|書類
docp.sub|Relatórios das usinas da sua carteira, termos da oferta e comprovantes.|Reports for the plants in your portfolio, offer terms and receipts.|Informes de las plantas de tu portafolio, términos de la oferta y comprobantes.|Rapports des centrales de votre portefeuille, conditions de l’offre et justificatifs.|Berichte zu Ihren Parks, Angebotsbedingungen und Belege.|您所持电站的报告、认购条款与凭证。|保有発電所のレポート、募集条件、証跡。
docp.empty|Sem documentos ainda. Os relatórios das usinas também ficam em|No documents yet. Plant reports are also available on|Aún sin documentos. Los informes de las plantas también están en|Pas encore de documents. Les rapports des centrales sont aussi sur|Noch keine Dokumente. Berichte finden Sie auch auf|暂无文件。电站报告也可在|書類はまだありません。発電所のレポートは
docp.emptyLink|cada página de usina|each plant page|cada página de planta|chaque page de centrale|jeder Park-Seite|各电站页面查看|各発電所ページにもあります
docp.cotasLine|{n} cotas · {city} - {uf}|{n} shares · {city} - {uf}|{n} participaciones · {city} - {uf}|{n} parts · {city} - {uf}|{n} Anteile · {city} - {uf}|{n} 份 · {city} - {uf}|{n} 口 · {city} - {uf}
docp.report|Relatório para o investidor (PDF, em português)|Investor report (PDF, in Portuguese)|Informe para el inversor (PDF, en portugués)|Rapport investisseur (PDF, en portugais)|Anlegerbericht (PDF, auf Portugiesisch)|投资者报告（PDF，葡萄牙语）|投資家向けレポート（PDF、ポルトガル語）
docp.reportPt|Relatório para o investidor (PDF)|Investor report (PDF)|Informe para el inversor (PDF)|Rapport investisseur (PDF)|Anlegerbericht (PDF)|投资者报告 (PDF)|投資家向けレポート (PDF)
docp.audit|Relatório de auditoria completo (PDF)|Full audit report (PDF)|Informe de auditoría completo (PDF)|Rapport d’audit complet (PDF)|Vollständiger Prüfbericht (PDF)|完整审计报告 (PDF)|完全版監査レポート (PDF)
docp.risks|Riscos e condições da oferta|Offer risks and terms|Riesgos y condiciones de la oferta|Risques et conditions de l’offre|Risiken und Angebotsbedingungen|认购风险与条款|募集のリスクと条件
docp.verify|Para conferir se um relatório é autêntico, use|To check that a report is authentic, use|Para comprobar si un informe es auténtico, usa|Pour vérifier l’authenticité d’un rapport, utilisez|Um die Echtheit eines Berichts zu prüfen, nutzen Sie|如需验证报告真伪，请使用|レポートの真正性を確認するには
docp.verifyLink|Verificar relatório|Verify a report|Verificar informe|Vérifier un rapport|Bericht prüfen|验证报告|「レポートを検証」をご利用ください
prof.title|Perfil|Profile|Perfil|Profil|Profil|个人资料|プロフィール
prof.sub|Sua carteira, sessão e verificação de identidade (KYC).|Your wallet, session and identity verification (KYC).|Tu billetera, sesión y verificación de identidad (KYC).|Votre portefeuille, votre session et la vérification d’identité (KYC).|Ihre Wallet, Sitzung und Identitätsprüfung (KYC).|您的钱包、会话与身份验证 (KYC)。|ウォレット、セッション、本人確認 (KYC)。
prof.wallet|Carteira|Wallet|Billetera|Portefeuille|Wallet|钱包|ウォレット
prof.address|Endereço|Address|Dirección|Adresse|Adresse|地址|アドレス
prof.network|Rede|Network|Red|Réseau|Netzwerk|网络|ネットワーク
prof.session|Sessão|Session|Sesión|Session|Sitzung|会话|セッション
prof.sessionOk|Confirmada por assinatura|Confirmed by signature|Confirmada por firma|Confirmée par signature|Per Signatur bestätigt|已签名确认|署名で確認済み
prof.sessionNo|Não confirmada|Not confirmed|No confirmada|Non confirmée|Nicht bestätigt|未确认|未確認
prof.confirm|Confirmar acesso|Confirm access|Confirmar acceso|Confirmer l’accès|Zugang bestätigen|确认访问|アクセスを確認
prof.kyc|KYC on-chain|On-chain KYC|KYC on-chain|KYC on-chain|On-Chain-KYC|链上 KYC|オンチェーン KYC
prof.kycNoReg|registro não implantado nesta rede|registry not deployed on this network|registro no implementado en esta red|registre non déployé sur ce réseau|Register in diesem Netzwerk nicht bereitgestellt|该网络未部署登记合约|このネットワークに登録コントラクトはありません
prof.kycOk|verificado|verified|verificado|vérifié|verifiziert|已验证|確認済み
prof.kycPending|pendente|pending|pendiente|en attente|ausstehend|待处理|保留中
prof.bscscan|Ver carteira no BscScan|View wallet on BscScan|Ver billetera en BscScan|Voir le portefeuille sur BscScan|Wallet auf BscScan ansehen|在 BscScan 查看钱包|BscScan でウォレットを表示
prof.safety|Nunca pedimos sua frase de recuperação. Toda transação é simulada antes e você confere o valor exato na carteira.|We never ask for your recovery phrase. Every transaction is simulated first and you check the exact amount in your wallet.|Nunca pedimos tu frase de recuperación. Cada transacción se simula antes y verificas el valor exacto en la billetera.|Nous ne demandons jamais votre phrase de récupération. Chaque transaction est simulée et vous vérifiez le montant exact dans le portefeuille.|Wir fragen nie nach Ihrer Wiederherstellungsphrase. Jede Transaktion wird vorab simuliert und Sie prüfen den genauen Betrag in der Wallet.|我们绝不索要助记词。每笔交易都会先模拟，您可在钱包中核对准确金额。|リカバリーフレーズを求めることはありません。すべての取引は事前にシミュレーションされ、ウォレットで正確な金額を確認できます。
prof.kycTitle|Verificação de identidade (KYC)|Identity verification (KYC)|Verificación de identidad (KYC)|Vérification d’identité (KYC)|Identitätsprüfung (KYC)|身份验证 (KYC)|本人確認 (KYC)
prof.kycSub|Exigida para investir e receber cotas.|Required to invest and receive shares.|Requerida para invertir y recibir participaciones.|Requise pour investir et recevoir des parts.|Erforderlich, um zu investieren und Anteile zu erhalten.|投资和领取份额前必须完成。|投資と持分の受け取りに必要です。
kyc.verified|Identidade verificada|Identity verified|Identidad verificada|Identité vérifiée|Identität verifiziert|身份已验证|本人確認済み
kyc.verifiedText|Sua carteira está habilitada no registro de investidores do contrato (IdentityRegistry).|Your wallet is enabled in the contract’s investor registry (IdentityRegistry).|Tu billetera está habilitada en el registro de inversores del contrato (IdentityRegistry).|Votre portefeuille est habilité dans le registre des investisseurs du contrat (IdentityRegistry).|Ihre Wallet ist im Anlegerregister des Vertrags freigeschaltet (IdentityRegistry).|您的钱包已在合约投资者登记 (IdentityRegistry) 中启用。|ウォレットはコントラクトの投資家登録 (IdentityRegistry) で有効化されています。
kyc.signFirst|Para enviar seus dados de KYC, primeiro prove que esta carteira é sua assinando uma mensagem (gratuito, sem transação).|To submit your KYC data, first prove this wallet is yours by signing a message (free, no transaction).|Para enviar tus datos de KYC, primero demuestra que esta billetera es tuya firmando un mensaje (gratis, sin transacción).|Pour envoyer vos données KYC, prouvez d’abord que ce portefeuille vous appartient en signant un message (gratuit, sans transaction).|Um KYC-Daten zu senden, weisen Sie zuerst per Signatur nach, dass die Wallet Ihnen gehört (kostenlos, keine Transaktion).|提交 KYC 资料前，请先签名一条消息以证明钱包归您所有（免费，不产生交易）。|KYC 情報を送信する前に、メッセージに署名してウォレットの所有を証明してください（無料、取引なし）。
kyc.confirming|Confirme na carteira…|Confirm in your wallet…|Confirma en la billetera…|Confirmez dans le portefeuille…|In der Wallet bestätigen…|请在钱包中确认…|ウォレットで承認してください…
kyc.signIn|Entrar com assinatura|Sign in with signature|Entrar con firma|Se connecter par signature|Mit Signatur anmelden|签名登录|署名でログイン
kyc.pending|KYC em análise|KYC under review|KYC en análisis|KYC en cours d’examen|KYC wird geprüft|KYC 审核中|KYC 審査中
kyc.pendingText|Pedido enviado em {d} ({name}, {doc}). Após aprovação, sua carteira é registrada on-chain e esta tela muda sozinha.|Request sent on {d} ({name}, {doc}). Once approved, your wallet is registered on-chain and this screen updates automatically.|Solicitud enviada el {d} ({name}, {doc}). Tras la aprobación, tu billetera se registra on-chain y esta pantalla cambia sola.|Demande envoyée le {d} ({name}, {doc}). Après approbation, votre portefeuille est enregistré on-chain et cet écran se met à jour.|Anfrage gesendet am {d} ({name}, {doc}). Nach Freigabe wird Ihre Wallet on-chain registriert und diese Ansicht aktualisiert sich.|申请已于 {d} 提交（{name}，{doc}）。审核通过后，您的钱包将在链上登记，本页面会自动更新。|{d} に申請済み（{name}、{doc}）。承認後、ウォレットがオンチェーン登録され、この画面は自動で更新されます。
kyc.name|Nome completo|Full name|Nombre completo|Nom complet|Vollständiger Name|姓名|氏名
kyc.country|País de residência fiscal|Country of tax residence|País de residencia fiscal|Pays de résidence fiscale|Steuerlicher Wohnsitz|税务居住国|税務上の居住国
kyc.cpf|CPF|CPF (Brazilian tax ID)|CPF (identificación fiscal brasileña)|CPF (identifiant fiscal brésilien)|CPF (brasilianische Steuer-ID)|CPF（巴西税号）|CPF（ブラジル納税者番号）
kyc.passport|Número do passaporte|Passport number|Número de pasaporte|Numéro de passeport|Reisepassnummer|护照号码|パスポート番号
kyc.passportLbl|Passaporte|Passport|Pasaporte|Passeport|Reisepass|护照|パスポート
kyc.email|E-mail|Email|Correo electrónico|E-mail|E-Mail|电子邮件|メールアドレス
kyc.consent|Autorizo o tratamento dos meus dados para verificação de identidade e prevenção à lavagem de dinheiro (LGPD, art. 7º, II e Lei 9.613/98) e declaro ciência dos riscos do investimento.|I authorize the processing of my data for identity verification and anti-money-laundering purposes (Brazil’s LGPD art. 7, II and Law 9,613/98) and acknowledge the investment risks.|Autorizo el tratamiento de mis datos para verificación de identidad y prevención del lavado de dinero (LGPD de Brasil, art. 7, II y Ley 9.613/98) y declaro conocer los riesgos de la inversión.|J’autorise le traitement de mes données pour la vérification d’identité et la lutte contre le blanchiment (LGPD brésilienne, art. 7, II et loi 9.613/98) et déclare avoir pris connaissance des risques.|Ich willige in die Verarbeitung meiner Daten zur Identitätsprüfung und Geldwäscheprävention ein (brasilianisches LGPD, Art. 7 II und Gesetz 9.613/98) und bestätige, die Anlagerisiken zu kennen.|我授权为身份验证和反洗钱目的处理我的数据（巴西 LGPD 第 7 条第 II 款及第 9.613/98 号法律），并已知悉投资风险。|本人確認およびマネーロンダリング防止のための個人データ処理（ブラジル LGPD 第 7 条 II、法律 9.613/98）に同意し、投資リスクを理解しました。
kyc.sending|Enviando…|Sending…|Enviando…|Envoi…|Wird gesendet…|发送中…|送信中…
kyc.submit|Enviar para verificação|Submit for verification|Enviar para verificación|Envoyer pour vérification|Zur Prüfung senden|提交审核|審査に送信
kyc.prodNote|Na versão de produção, esta etapa inclui validação de documento e prova de vida por um provedor de KYC.|In production, this step includes document validation and liveness check by a KYC provider.|En la versión de producción, esta etapa incluye validación de documento y prueba de vida por un proveedor de KYC.|En production, cette étape inclut la validation du document et une preuve de vie par un prestataire KYC.|Im Produktivbetrieb umfasst dieser Schritt Dokumentenprüfung und Lebenderkennung durch einen KYC-Anbieter.|正式版中，此步骤包括由 KYC 服务商进行证件验证与活体检测。|本番環境では、KYC 事業者による書類確認と生体確認が含まれます。
kyc.failed|Não foi possível enviar.|Could not submit.|No se pudo enviar.|Envoi impossible.|Senden fehlgeschlagen.|提交失败。|送信できませんでした。
kyc.badCpf|CPF inválido.|Invalid CPF.|CPF inválido.|CPF invalide.|Ungültige CPF.|CPF 无效。|CPF が無効です。
kyc.foreignNote|Investidores não residentes no Brasil passam por análise adicional de conformidade antes da aprovação.|Investors not resident in Brazil undergo an additional compliance review before approval.|Los inversores no residentes en Brasil pasan por un análisis adicional de cumplimiento antes de la aprobación.|Les investisseurs non résidents au Brésil font l’objet d’un examen de conformité supplémentaire avant approbation.|Anleger ohne Wohnsitz in Brasilien durchlaufen vor der Freigabe eine zusätzliche Compliance-Prüfung.|非巴西居民投资者在审核通过前需接受额外的合规审查。|ブラジル非居住者の投資家は、承認前に追加のコンプライアンス審査を受けます。
sup.title|Suporte|Support|Soporte|Assistance|Support|支持|サポート
sup.sub|Dúvidas frequentes e contato com a equipe.|FAQ and contact with our team.|Preguntas frecuentes y contacto con el equipo.|Questions fréquentes et contact avec l’équipe.|Häufige Fragen und Kontakt zum Team.|常见问题与联系团队。|よくある質問とお問い合わせ。
sup.q1|Como recebo as distribuições?|How do I receive distributions?|¿Cómo recibo las distribuciones?|Comment je reçois les distributions ?|Wie erhalte ich Ausschüttungen?|如何获得收益分配？|分配はどう受け取りますか？
sup.a1|A receita líquida da usina é distribuída em USDT na proporção das suas cotas. O valor fica disponível no contrato e você resgata quando quiser, em Meu portfólio.|The plant’s net revenue is distributed in USDT pro rata to your shares. It stays available in the contract and you claim it whenever you like, in My portfolio.|El ingreso neto de la planta se distribuye en USDT en proporción a tus participaciones. Queda disponible en el contrato y lo rescatas cuando quieras, en Mi portafolio.|Le revenu net de la centrale est distribué en USDT au prorata de vos parts. Il reste disponible dans le contrat et vous le retirez quand vous voulez, dans Mon portefeuille.|Der Nettoerlös des Parks wird anteilig in USDT ausgeschüttet. Er liegt im Vertrag bereit und Sie holen ihn jederzeit unter „Mein Portfolio“ ab.|电站净收入按您的份额比例以 USDT 分配，资金保存在合约中，您可随时在“我的投资组合”中领取。|発電所の純収益は持分に応じて USDT で分配されます。金額はコントラクトに保管され、マイポートフォリオからいつでも受け取れます。
sup.q2|Posso desistir do investimento?|Can I withdraw my investment?|¿Puedo desistir de la inversión?|Puis-je me rétracter ?|Kann ich von der Investition zurücktreten?|可以撤回投资吗？|投資を撤回できますか？
sup.a2|Sim: até 5 dias após cada aporte, com devolução integral pelo contrato. Se a oferta não atingir a meta mínima, todos recebem o valor de volta.|Yes: up to 5 days after each investment, with a full refund by the contract. If the offer misses its minimum target, everyone is refunded.|Sí: hasta 5 días después de cada aporte, con devolución total por el contrato. Si la oferta no alcanza la meta mínima, todos reciben su dinero.|Oui : jusqu’à 5 jours après chaque apport, avec remboursement intégral par le contrat. Si l’offre n’atteint pas son objectif minimum, tout le monde est remboursé.|Ja: bis 5 Tage nach jeder Einzahlung, mit voller Rückzahlung durch den Vertrag. Wird das Mindestziel verfehlt, erhalten alle ihr Geld zurück.|可以：每笔投资后 5 天内可撤回，由合约全额退还。若认购未达最低目标，所有人都将获得退款。|はい。各投資から 5 日以内なら、コントラクトにより全額返金されます。最低目標に届かない場合も全員に返金されます。
sup.q3|Que carteira devo usar?|Which wallet should I use?|¿Qué billetera debo usar?|Quel portefeuille utiliser ?|Welche Wallet sollte ich nutzen?|应使用哪种钱包？|どのウォレットを使えばよいですか？
sup.a3|Qualquer carteira compatível com a BNB Chain (Binance Wallet, MetaMask, Rabby, Trust). Recomendamos carteira de hardware para valores altos.|Any BNB Chain–compatible wallet (Binance Wallet, MetaMask, Rabby, Trust). We recommend a hardware wallet for large amounts.|Cualquier billetera compatible con BNB Chain (Binance Wallet, MetaMask, Rabby, Trust). Recomendamos una billetera de hardware para montos altos.|Tout portefeuille compatible BNB Chain (Binance Wallet, MetaMask, Rabby, Trust). Un portefeuille matériel est recommandé pour les gros montants.|Jede BNB-Chain-kompatible Wallet (Binance Wallet, MetaMask, Rabby, Trust). Für hohe Beträge empfehlen wir eine Hardware-Wallet.|任何兼容 BNB Chain 的钱包（Binance Wallet、MetaMask、Rabby、Trust）。大额投资建议使用硬件钱包。|BNB Chain 対応のウォレット（Binance Wallet、MetaMask、Rabby、Trust）。高額の場合はハードウェアウォレットを推奨します。
sup.q4|Os rendimentos são garantidos?|Are returns guaranteed?|¿Los rendimientos están garantizados?|Les rendements sont-ils garantis ?|Sind die Renditen garantiert?|收益有保证吗？|収益は保証されますか？
sup.a4|Não. As rentabilidades são projeções de modelos com dados abertos e dependem da geração, da tarifa e da adimplência dos assinantes.|No. Returns are model projections based on open data and depend on generation, tariffs and subscriber payments.|No. Las rentabilidades son proyecciones de modelos con datos abiertos y dependen de la generación, la tarifa y el pago de los suscriptores.|Non. Les rendements sont des projections de modèles sur données ouvertes et dépendent de la production, du tarif et des paiements des abonnés.|Nein. Renditen sind Modellprognosen auf Basis offener Daten und hängen von Erzeugung, Tarif und Zahlungen der Abnehmer ab.|不保证。收益率是基于公开数据的模型预测，取决于发电量、电价和用户付款情况。|いいえ。利回りはオープンデータに基づくモデル予測で、発電量・電力料金・契約者の支払い状況に左右されます。
sup.q5|Como sei que o relatório é verdadeiro?|How do I know the report is genuine?|¿Cómo sé que el informe es verdadero?|Comment savoir si le rapport est authentique ?|Woher weiß ich, dass der Bericht echt ist?|如何确认报告真实？|レポートが本物だとどうわかりますか？
sup.a5|Cada PDF leva os dados anexados e um hash SHA-256 registrado no contrato da usina. Confira em Verificar relatório.|Each PDF carries its data attached and a SHA-256 hash recorded in the plant’s contract. Check it on Verify a report.|Cada PDF lleva los datos adjuntos y un hash SHA-256 registrado en el contrato de la planta. Compruébalo en Verificar informe.|Chaque PDF contient ses données en pièce jointe et un hash SHA-256 enregistré dans le contrat de la centrale. Vérifiez-le dans Vérifier un rapport.|Jedes PDF enthält die Daten als Anhang und einen SHA-256-Hash im Vertrag des Parks. Prüfen Sie ihn unter „Bericht prüfen“.|每份 PDF 都附带数据以及记录在电站合约中的 SHA-256 哈希，可在“验证报告”中核对。|各 PDF にはデータが添付され、SHA-256 ハッシュが発電所のコントラクトに記録されています。「レポートを検証」で確認できます。
sup.questions|Dúvidas?|Questions?|¿Dudas?|Des questions ?|Fragen?|有疑问？|ご質問は？
sup.team|Nossa equipe está pronta para te ajudar.|Our team is ready to help.|Nuestro equipo está listo para ayudarte.|Notre équipe est prête à vous aider.|Unser Team hilft Ihnen gern.|我们的团队随时为您服务。|担当チームがサポートします。
sup.security|Segurança e contratos|Security and contracts|Seguridad y contratos|Sécurité et contrats|Sicherheit und Verträge|安全与合约|セキュリティと契約
kyc.approved|Identidade aprovada|Identity approved|Identidad aprobada|Identité approuvée|Identität bestätigt|身份已通过|本人確認が完了しました
kyc.approvedText|Sua carteira foi registrada no cadastro de investidores do contrato. Já pode investir.|Your wallet was registered in the contract’s investor registry. You can invest now.|Tu billetera fue registrada en el registro de inversores del contrato. Ya puedes invertir.|Votre portefeuille a été enregistré dans le registre des investisseurs du contrat. Vous pouvez investir.|Ihre Wallet wurde im Anlegerregister des Vertrags eingetragen. Sie können jetzt investieren.|您的钱包已登记到合约投资者名册，现在可以投资。|ウォレットがコントラクトの投資家登録に記録されました。投資できます。
kyc.approving|Registrando na blockchain…|Registering on the blockchain…|Registrando en la blockchain…|Enregistrement sur la blockchain…|Wird in der Blockchain eingetragen…|正在区块链上登记…|ブロックチェーンに登録中…
kyc.testnetAuto|Testnet: a aprovação é automática para demonstração. Na rede principal, a verificação é feita por um provedor de KYC.|Testnet: approval is automatic for demonstration. On mainnet, verification is done by a KYC provider.|Testnet: la aprobación es automática para la demostración. En la red principal, la verificación la hace un proveedor de KYC.|Testnet : l’approbation est automatique pour la démonstration. Sur le réseau principal, la vérification est faite par un prestataire KYC.|Testnet: Die Freigabe erfolgt zu Demozwecken automatisch. Im Hauptnetz prüft ein KYC-Anbieter.|测试网：为演示自动通过。主网上由 KYC 服务商审核。|テストネット：デモのため自動で承認されます。メインネットでは KYC 事業者が確認します。
kyc.retry|Tentar novamente|Try again|Intentar de nuevo|Réessayer|Erneut versuchen|重试|再試行
"""
